using System;
using System.Collections.Generic;
using OneRoof.Application.Tower;
using OneRoof.Content;
using OneRoof.Domain.Time;
using OneRoof.Domain.Topology;
using OneRoof.Presentation.Population;
using UnityEngine;
using Object = UnityEngine.Object;

namespace OneRoof.Presentation.Tower
{
    /// <summary>
    /// Deep presenter responsible for the autogenerated building exterior envelope,
    /// vertical facade cutaways, ground lobby entrance canopy, roof deck, parapets,
    /// mechanical fixtures (penthouse, HVAC, antenna), and the outside weather stage.
    /// Pure presentation layer: consumes TowerTopologyProjection with 0 domain mutations.
    /// </summary>
    public sealed class BuildingExteriorPresenter
    {
        public const float WallThickness = 0.36f;
        public const float CladdingThickness = 0.08f;
        public const float SpandrelProtrusion = 0.06f;
        public const float CorniceOverhang = 0.18f;
        public const float RoofDeckThickness = 0.28f;
        public const float ParapetHeight = 0.42f;

        // The tower camera sits on negative Z and looks toward positive Z,
        // so smaller Z values are closer to the camera.
        private const float EarthTileZ = 0.44f;
        private const float EarthDetailZ = 0.42f;
        private const float ExcavationZ = 0.38f;
        private const float LairFloorZ = 0.34f;

        private Transform _parent;
        private Material _worldMaterial;
        private Material _coneMaterial;
        private MaterialPropertyBlock _colorBlock;

        private Transform _root;
        private Transform _leftFacadeRoot;
        private Transform _rightFacadeRoot;
        private Transform _rooflineRoot;
        private Transform _fixturesRoot;
        private Transform _terracesRoot;
        private Transform _volumetricLightRoot;
        private Transform _groundRoot;

        private readonly List<GameObject> _leftWallSlices = new List<GameObject>();
        private readonly List<GameObject> _rightWallSlices = new List<GameObject>();
        private readonly List<GameObject> _leftSpandrels = new List<GameObject>();
        private readonly List<GameObject> _rightSpandrels = new List<GameObject>();
        private readonly List<GameObject> _terraceObjects = new List<GameObject>();
        private readonly List<GameObject> _roofObjects = new List<GameObject>();

        private readonly List<GameObject> _leftWindowFrames = new List<GameObject>();
        private readonly List<GameObject> _leftWindowGlasses = new List<GameObject>();
        private readonly List<GameObject> _leftWindowSills = new List<GameObject>();
        private readonly List<GameObject> _rightWindowFrames = new List<GameObject>();
        private readonly List<GameObject> _rightWindowGlasses = new List<GameObject>();
        private readonly List<GameObject> _rightWindowSills = new List<GameObject>();
        private readonly List<GameObject> _volumetricCones = new List<GameObject>();
        private readonly List<Mesh> _coneMeshes = new List<Mesh>();
        private readonly List<WindowLightingEntry> _windowLightingEntries = new List<WindowLightingEntry>();
        private readonly Dictionary<UndergroundCell, GameObject> _excavationViews = new Dictionary<UndergroundCell, GameObject>();
        private readonly Dictionary<UndergroundCell, GameObject> _lairFloorViews = new Dictionary<UndergroundCell, GameObject>();
        private readonly Dictionary<UndergroundCell, GameObject> _corridorViews = new Dictionary<UndergroundCell, GameObject>();
        private readonly Dictionary<UndergroundCell, GameObject> _shaftViews = new Dictionary<UndergroundCell, GameObject>();
        private readonly Dictionary<int, GameObject> _undergroundRoomViews = new Dictionary<int, GameObject>();
        private readonly Dictionary<int, NpcSkeletalHierarchy> _undergroundCrewViews = new Dictionary<int, NpcSkeletalHierarchy>();
        public IReadOnlyCollection<int> VisibleUndergroundCrewResidentIds => _undergroundCrewViews.Keys;
        private GameObject _accessCoreView;
        private int _renderedUndergroundRevision = -1;

        private int _renderedFloorCount = -1;
        private CellBounds _renderedGroundSlab;
        private CellBounds _renderedTopSlab;
        private OutsideStageBounds _stageBounds;

        public OutsideStageBounds StageBounds => _stageBounds;
        public int RenderedFloorCount => _renderedFloorCount;
        public Transform Root => _root;
        public Transform VolumetricLightRoot => _volumetricLightRoot;

        public IReadOnlyList<GameObject> LeftWindowFrames => _leftWindowFrames;
        public IReadOnlyList<GameObject> LeftWindowGlasses => _leftWindowGlasses;
        public IReadOnlyList<GameObject> LeftWindowSills => _leftWindowSills;
        public IReadOnlyList<GameObject> RightWindowFrames => _rightWindowFrames;
        public IReadOnlyList<GameObject> RightWindowGlasses => _rightWindowGlasses;
        public IReadOnlyList<GameObject> RightWindowSills => _rightWindowSills;
        public IReadOnlyList<GameObject> VolumetricCones => _volumetricCones;

        // Palette
        private static readonly Color WallCoreColor = new Color(0.18f, 0.22f, 0.28f);
        private static readonly Color CladdingColor = new Color(0.32f, 0.40f, 0.50f);
        private static readonly Color SpandrelColor = new Color(0.28f, 0.35f, 0.44f);
        private static readonly Color PlinthColor = new Color(0.12f, 0.15f, 0.19f);
        private static readonly Color RoofDeckColor = new Color(0.22f, 0.28f, 0.36f);
        private static readonly Color RoofBallastColor = new Color(0.13f, 0.16f, 0.22f);
        private static readonly Color CorniceTrimColor = new Color(0.38f, 0.46f, 0.58f);
        private static readonly Color CanopyColor = new Color(0.24f, 0.32f, 0.40f);
        private static readonly Color DownspoutColor = new Color(0.20f, 0.26f, 0.32f);
        private static readonly Color FixtureMetalColor = new Color(0.30f, 0.38f, 0.46f);
        private static readonly Color BeaconGlowColor = new Color(1.0f, 0.25f, 0.15f);

        public static readonly Color WindowFrameColor = new Color(0.24f, 0.30f, 0.38f);
        public static readonly Color WindowSillColor = new Color(0.34f, 0.42f, 0.52f);
        public static readonly Color WindowDayColor = new Color(0.35f, 0.52f, 0.65f, 0.70f);
        public static readonly Color WindowNightLitColor = new Color(1.00f, 0.74f, 0.38f, 0.95f);
        public static readonly Color WindowNightDarkColor = new Color(0.12f, 0.15f, 0.20f, 0.75f);
        public static readonly Color ConeDayColor = new Color(0.92f, 0.96f, 1.0f, 0.20f);
        public static readonly Color ConeNightLitColor = new Color(1.00f, 0.78f, 0.38f, 0.32f);
        public static readonly Color ConeNightDarkColor = new Color(0f, 0f, 0f, 0f);

        private readonly struct WindowLightingEntry
        {
            public readonly MeshRenderer GlassRenderer;
            public readonly MeshRenderer ConeRenderer;
            public readonly int Floor;
            public readonly bool IsLeft;

            public WindowLightingEntry(MeshRenderer glassRenderer, MeshRenderer coneRenderer, int floor, bool isLeft)
            {
                GlassRenderer = glassRenderer;
                ConeRenderer = coneRenderer;
                Floor = floor;
                IsLeft = isLeft;
            }
        }

        public void Initialize(Transform parent, Material worldMaterial, MaterialPropertyBlock colorBlock)
        {
            _parent = parent;
            _worldMaterial = worldMaterial;
            _colorBlock = colorBlock ?? new MaterialPropertyBlock();

            // Keep structural geometry depth writing. Making the shared material
            // transparent also changes rooms, floors and the outside city, so
            // distant quads can sort over the lobby and hide small lights.
            if (_worldMaterial != null && _coneMaterial == null)
            {
                _coneMaterial = new Material(_worldMaterial) { name = "Exterior Light Cones" };
                _coneMaterial.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
                _coneMaterial.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
                _coneMaterial.SetInt("_ZWrite", 0);
                _coneMaterial.renderQueue = (int)UnityEngine.Rendering.RenderQueue.Transparent;
                _coneMaterial.SetOverrideTag("RenderType", "Transparent");
            }

            Clear();
        }

        public void EnsureExteriorViews(TowerTopologyProjection topology, UndergroundDigProjection underground = null)
        {
            if (_parent == null || _worldMaterial == null) return;
            var floorCount = topology != null ? topology.FloorCount : TowerStructurePresenter.InitialFloorCount;
            if (floorCount <= 0) return;

            CellBounds groundSlab = default;
            CellBounds topSlab = default;
            if (topology != null)
            {
                if (!topology.TryGetFloorSlab(0, out groundSlab)) groundSlab = new CellBounds(0, -14, 17);
                if (!topology.TryGetFloorSlab(floorCount - 1, out topSlab))
                    topSlab = new CellBounds(floorCount - 1, -14, 17);
            }
            else
            {
                groundSlab = new CellBounds(0, -14, 17);
                topSlab = new CellBounds(floorCount - 1, -14, 17);
            }

            var geometryUnchanged = _root != null && _renderedFloorCount == floorCount &&
                _renderedGroundSlab.Equals(groundSlab) && _renderedTopSlab.Equals(topSlab);
            if (geometryUnchanged)
            {
                if (underground == null || underground.Revision != _renderedUndergroundRevision)
                {
                    SyncExcavationViews(underground);
                    SyncUndergroundStructures(underground);
                    _renderedUndergroundRevision = underground?.Revision ?? -1;
                }
                return;
            }

            EnsureHierarchyRoots();
            _renderedFloorCount = floorCount;
            _renderedGroundSlab = groundSlab;
            _renderedTopSlab = topSlab;

            BuildFacades(topology, floorCount);
            BuildGroundDressing(groundSlab);
            SyncExcavationViews(underground);
            SyncUndergroundStructures(underground);
            _renderedUndergroundRevision = underground?.Revision ?? -1;
            EnsureExteriorWindows(topology, floorCount);
            BuildRoofline(topology, floorCount, topSlab);
            BuildSetbackTerraces(topology, floorCount);
            CalculateStageBounds(floorCount, groundSlab, topSlab);
        }

        private void EnsureHierarchyRoots()
        {
            if (_root != null) return;

            var existing = _parent.Find("Building Exterior Envelope");
            if (existing != null)
            {
                _root = existing;
            }
            else
            {
                _root = new GameObject("Building Exterior Envelope").transform;
                _root.SetParent(_parent, false);
            }

            _leftFacadeRoot = EnsureChildTransform(_root, "Left Facade");
            _rightFacadeRoot = EnsureChildTransform(_root, "Right Facade");
            _rooflineRoot = EnsureChildTransform(_root, "Roofline & Capping");
            _fixturesRoot = EnsureChildTransform(_rooflineRoot, "Rooftop Fixtures");
            _terracesRoot = EnsureChildTransform(_root, "Setback Terraces");
            _volumetricLightRoot = EnsureChildTransform(_root, "Exterior Volumetric Lighting");
            _groundRoot = EnsureChildTransform(_root, "Ground Dressing");
        }

        private static Transform EnsureChildTransform(Transform parent, string name)
        {
            var child = parent.Find(name);
            if (child != null) return child;
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);
            return go.transform;
        }

        private void BuildFacades(TowerTopologyProjection topology, int floorCount)
        {
            // 1. Foundation Plinth (Left side)
            var ground = topology != null && topology.TryGetFloorSlab(0, out var g) ? g : new CellBounds(0, -14, 16);
            var groundLeft = -2.4f + ground.MinX * 0.5f;
            var groundBaseline = TowerStructurePresenter.FloorY(0) - 0.74f;

            UpdateOrCreateQuad(_leftFacadeRoot, "Left Foundation Plinth", PlinthColor,
                new Vector3(groundLeft - WallThickness * 0.5f - 0.04f, groundBaseline - 0.24f, 0.10f),
                new Vector2(WallThickness + 0.08f, 0.48f));

            // Anchor the upper downspout to the upper facade. The ground slab can
            // expand independently, and must not pull a vertical line through the
            // open setback beside the tower.
            var topFloorY = TowerStructurePresenter.FloorY(floorCount - 1) + 1.01f;
            if (floorCount > 1)
            {
                var firstUpper = topology != null && topology.TryGetFloorSlab(1, out var upper)
                    ? upper : new CellBounds(1, -14, 16);
                var upperLeft = -2.4f + firstUpper.MinX * 0.5f;
                var downspoutBottom = TowerStructurePresenter.FloorY(1) - 0.74f;
                UpdateOrCreateQuad(_leftFacadeRoot, "Left Downspout", DownspoutColor,
                    new Vector3(upperLeft - WallThickness - 0.02f, (downspoutBottom + topFloorY) * 0.5f, -0.05f),
                    new Vector2(0.04f, topFloorY - downspoutBottom));
            }

            // Per-Floor Left Wall Slices & Spandrels
            for (var f = 0; f < floorCount; f++)
            {
                var slab = topology != null && topology.TryGetFloorSlab(f, out var s) ? s : new CellBounds(f, -14, 16);
                var worldLeft = -2.4f + slab.MinX * 0.5f;
                var floorY = TowerStructurePresenter.FloorY(f);
                var baselineY = floorY - 0.74f;

                // Wall Section
                var wallObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Wall {f}", WallCoreColor,
                    new Vector3(worldLeft - WallThickness * 0.5f, floorY, 0.10f),
                    new Vector2(WallThickness, 1.75f));
                if (!_leftWallSlices.Contains(wallObj)) _leftWallSlices.Add(wallObj);

                // Outer Weather Trim
                UpdateOrCreateQuad(_leftFacadeRoot, $"Left Cladding {f}", CladdingColor,
                    new Vector3(worldLeft - WallThickness + CladdingThickness * 0.5f, floorY, -0.04f),
                    new Vector2(CladdingThickness, 1.75f));

                // Horizontal Spandrel Plate
                var spandrelObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Spandrel {f}", SpandrelColor,
                    new Vector3(worldLeft - (WallThickness + SpandrelProtrusion) * 0.5f, baselineY, 0.08f),
                    new Vector2(WallThickness + SpandrelProtrusion, 0.18f));
                if (!_leftSpandrels.Contains(spandrelObj)) _leftSpandrels.Add(spandrelObj);
            }

            // Right Facade
            // Floor 0 Lobby Entrance Threshold & Cantilever Awning
            var groundRight = -2.4f + (ground.MaxX + 1) * 0.5f;
            UpdateOrCreateQuad(_rightFacadeRoot, "Lobby Entrance Portal Frame", CladdingColor,
                new Vector3(groundRight - 0.05f, TowerStructurePresenter.FloorY(0), 0.10f),
                new Vector2(0.10f, 1.55f));

            UpdateOrCreateQuad(_rightFacadeRoot, "Lobby Cantilever Canopy", CanopyColor,
                new Vector3(groundRight + 0.65f, groundBaseline + 1.28f, 0.38f),
                new Vector2(1.40f, 0.14f));

            // A framed, lit street entrance stays outside the walkable lobby.
            var entranceX = groundRight + 0.42f;
            var floorY0 = TowerStructurePresenter.FloorY(0);
            UpdateOrCreateQuad(_rightFacadeRoot, "Entrance Glass", new Color(0.16f, 0.32f, 0.39f),
                new Vector3(entranceX, floorY0 - 0.12f, 0.17f), new Vector2(0.70f, 1.12f));
            UpdateOrCreateQuad(_rightFacadeRoot, "Entrance Left Jamb", CorniceTrimColor,
                new Vector3(entranceX - 0.39f, floorY0 - 0.08f, 0.04f), new Vector2(0.07f, 1.32f));
            UpdateOrCreateQuad(_rightFacadeRoot, "Entrance Right Jamb", CorniceTrimColor,
                new Vector3(entranceX + 0.39f, floorY0 - 0.08f, 0.04f), new Vector2(0.07f, 1.32f));
            UpdateOrCreateQuad(_rightFacadeRoot, "Entrance Lintel", CorniceTrimColor,
                new Vector3(entranceX, floorY0 + 0.61f, 0.02f), new Vector2(0.86f, 0.10f));
            UpdateOrCreateQuad(_rightFacadeRoot, "Entrance Door Seam", new Color(0.54f, 0.72f, 0.70f),
                new Vector3(entranceX, floorY0 - 0.13f, -0.02f), new Vector2(0.025f, 1.08f));
            UpdateOrCreateQuad(_rightFacadeRoot, "Entrance Light", new Color(1f, 0.76f, 0.38f),
                new Vector3(entranceX, floorY0 + 0.77f, -0.06f), new Vector2(0.24f, 0.055f));
            UpdateOrCreateQuad(_rightFacadeRoot, "Entrance Sign Panel", new Color(0.10f, 0.25f, 0.27f),
                new Vector3(entranceX, floorY0 + 0.87f, 0.08f), new Vector2(1.05f, 0.22f));
            UpdateOrCreateQuad(_rightFacadeRoot, "Entrance Sign Mark", new Color(0.48f, 0.91f, 0.68f),
                new Vector3(entranceX, floorY0 + 0.87f, -0.02f), new Vector2(0.42f, 0.045f));

            // Upper Floor Right Wall Slices
            for (var f = 1; f < floorCount; f++)
            {
                var slab = topology != null && topology.TryGetFloorSlab(f, out var s) ? s : new CellBounds(f, -14, 16);
                var worldRight = -2.4f + (slab.MaxX + 1) * 0.5f;
                var floorY = TowerStructurePresenter.FloorY(f);
                var baselineY = floorY - 0.74f;

                var wallObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Wall {f}", WallCoreColor,
                    new Vector3(worldRight + WallThickness * 0.5f, floorY, 0.10f),
                    new Vector2(WallThickness, 1.75f));
                if (!_rightWallSlices.Contains(wallObj)) _rightWallSlices.Add(wallObj);

                UpdateOrCreateQuad(_rightFacadeRoot, $"Right Cladding {f}", CladdingColor,
                    new Vector3(worldRight + WallThickness - CladdingThickness * 0.5f, floorY, -0.04f),
                    new Vector2(CladdingThickness, 1.75f));

                var spandrelObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Spandrel {f}", SpandrelColor,
                    new Vector3(worldRight + (WallThickness + SpandrelProtrusion) * 0.5f, baselineY, 0.08f),
                    new Vector2(WallThickness + SpandrelProtrusion, 0.18f));
                if (!_rightSpandrels.Contains(spandrelObj)) _rightSpandrels.Add(spandrelObj);
            }

            // Downspout Right (from Floor 1 to Ground Canopy)
            if (floorCount > 1)
            {
                var f1Slab = topology != null && topology.TryGetFloorSlab(1, out var s1) ? s1 : new CellBounds(1, -14, 16);
                var f1Right = -2.4f + (f1Slab.MaxX + 1) * 0.5f;
                var downHeightR = topFloorY - (TowerStructurePresenter.FloorY(1) - 0.74f);
                var downCenterR = ((TowerStructurePresenter.FloorY(1) - 0.74f) + topFloorY) * 0.5f;
                UpdateOrCreateQuad(_rightFacadeRoot, "Right Downspout", DownspoutColor,
                    new Vector3(f1Right + WallThickness + 0.02f, downCenterR, -0.05f),
                    new Vector2(0.04f, downHeightR));
            }
        }

        private void BuildGroundDressing(CellBounds ground)
        {
            var left = -2.4f + ground.MinX * 0.5f;
            var right = -2.4f + (ground.MaxX + 1) * 0.5f;
            var baseline = TowerStructurePresenter.FloorY(0) - 0.74f;
            var width = right - left;
            var center = (left + right) * 0.5f;
            var earthWidth = UndergroundDigState.GridWidthCells * GridPlacementController.UndergroundCellSize;
            var earthLeft = center - earthWidth * 0.5f;
            var earthDepth = UndergroundDigState.MaxDepthCells * GridPlacementController.UndergroundCellSize;

            // Keep cell art in front of the soil backing so the earth grid
            // remains visible and excavation can reveal a real change.

            // The lair board has its own bounds and remains a centered field beneath
            // the tower, independent of tower-floor slab placement and expansion.
            UpdateOrCreateQuad(_groundRoot, "Foundation Soil", new Color(0.25f, 0.16f, 0.10f),
                new Vector3(center, baseline - earthDepth * 0.5f, 0.48f), new Vector2(earthWidth, earthDepth));
            // Room-scale underground squares make both the dig target and the resulting
            // open space readable at the same scale as a small tower room.
            for (var depth = 0; depth < UndergroundDigState.MaxDepthCells; depth++)
            for (var column = 0; column < UndergroundDigState.GridWidthCells; column++)
            {
                var x = earthLeft + (column + 0.5f) * GridPlacementController.UndergroundCellSize;
                var y = baseline - (depth + 0.5f) * GridPlacementController.UndergroundCellSize;
                // Bands mark the four basement levels without making each cell
                // look like a separate floating brick.
                var band = depth / 3;
                var shade = ((column * 7 + depth * 3) % 5) * 0.012f;
                var earthColor = new Color(0.48f - band * 0.045f + shade,
                    0.30f - band * 0.028f + shade * 0.5f,
                    0.18f - band * 0.012f);
                UpdateOrCreateQuad(_groundRoot, $"Earth Grid {column}_{depth}", earthColor,
                    new Vector3(x, y, EarthTileZ), new Vector2(1.002f, 1.002f));
            }
            for (var level = 1; level < 4; level++)
                UpdateOrCreateQuad(_groundRoot, $"Earth Stratum {level}", new Color(0.22f, 0.15f, 0.11f),
                    new Vector3(center, baseline - level * 3f, EarthDetailZ), new Vector2(earthWidth, 0.065f));
            for (var i = 0; i < 16; i++)
            {
                var depositX = earthLeft + earthWidth * ((i + 1f) / 17f);
                var depositY = baseline - 0.55f - (i % UndergroundDigState.MaxDepthCells) * 0.82f;
                var depositWidth = 0.18f + (i % 3) * 0.09f;
                var depositColor = i % 2 == 0
                    ? new Color(0.29f, 0.19f, 0.12f)
                    : new Color(0.17f, 0.11f, 0.08f);
                UpdateOrCreateQuad(_groundRoot, $"Earth Deposit {i}", depositColor,
                    new Vector3(depositX, depositY, EarthDetailZ), new Vector2(depositWidth, 0.07f));
            }
            UpdateOrCreateQuad(_groundRoot, "Foundation Stone", new Color(0.18f, 0.27f, 0.23f),
                new Vector3(center, baseline - 0.10f, 0.46f), new Vector2(width, 0.17f));
            UpdateOrCreateQuad(_groundRoot, "Ground Green Edge", new Color(0.16f, 0.36f, 0.27f),
                new Vector3(center, baseline + 0.012f, 0.02f), new Vector2(width, 0.035f));
            for (var i = 0; i < 5; i++)
            {
                var x = left + 0.55f + i * Mathf.Max(0.25f, (width - 1.1f) / 4f);
                UpdateOrCreateQuad(_groundRoot, $"Foundation Pier {i}", new Color(0.21f, 0.31f, 0.27f),
                    new Vector3(x, baseline - 0.36f, 0.46f), new Vector2(0.12f, 0.55f));
            }

            // These quiet wall bays sit in front of the slab (z=1) but behind
            // actual room backdrops (z=0.7), so new rooms naturally cover them.
            const float shaftLeft = -2.4f;
            var westSpan = shaftLeft - left;
            if (westSpan > 2f)
            {
                var baySpacing = westSpan / 6f;
                for (var i = 1; i <= 5; i++)
                {
                    var bayX = left + baySpacing * i;
                    UpdateOrCreateQuad(_groundRoot, $"West Bay Mullion {i}", new Color(0.12f, 0.27f, 0.25f),
                        new Vector3(bayX, TowerStructurePresenter.FloorY(0), 0.91f), new Vector2(0.035f, 1.16f));
                    UpdateOrCreateQuad(_groundRoot, $"West Bay Marker {i}", new Color(0.40f, 0.52f, 0.39f),
                        new Vector3(bayX - baySpacing * 0.5f, TowerStructurePresenter.FloorY(0) + 0.56f, 0.90f),
                        new Vector2(0.10f, 0.035f));
                }
            }

            var apronX = right + 1.05f;
            UpdateOrCreateQuad(_groundRoot, "Entrance Paving", new Color(0.32f, 0.42f, 0.40f),
                new Vector3(apronX, baseline - 0.03f, 0.13f), new Vector2(2.1f, 0.11f));
            UpdateOrCreateQuad(_groundRoot, "Entrance Step Highlight", new Color(0.55f, 0.70f, 0.62f),
                new Vector3(right + 0.43f, baseline + 0.04f, 0.01f), new Vector2(0.86f, 0.045f));
            UpdateOrCreateQuad(_groundRoot, "Entrance Planter", new Color(0.21f, 0.37f, 0.30f),
                new Vector3(right + 1.70f, baseline + 0.18f, 0.02f), new Vector2(0.42f, 0.28f));
            UpdateOrCreateQuad(_groundRoot, "Entrance Greenery", new Color(0.39f, 0.68f, 0.40f),
                new Vector3(right + 1.70f, baseline + 0.43f, -0.01f), new Vector2(0.30f, 0.32f));
        }

        private void SyncExcavationViews(UndergroundDigProjection underground)
        {
            var active = new HashSet<UndergroundCell>();
            var floored = new HashSet<UndergroundCell>();
            if (underground != null)
            {
                for (var i = 0; i < underground.ExcavatedCells.Count; i++)
                    active.Add(underground.ExcavatedCells[i]);
                for (var i = 0; i < underground.FlooredCells.Count; i++)
                    floored.Add(underground.FlooredCells[i]);
            }

            var retired = new List<UndergroundCell>();
            foreach (var pair in _excavationViews)
            {
                if (!active.Contains(pair.Key))
                {
                    if (pair.Value != null)
                    {
                        if (UnityEngine.Application.isPlaying) Object.Destroy(pair.Value);
                        else Object.DestroyImmediate(pair.Value);
                    }
                    retired.Add(pair.Key);
                }
            }
            for (var i = 0; i < retired.Count; i++) _excavationViews.Remove(retired[i]);

            retired.Clear();
            foreach (var pair in _lairFloorViews)
            {
                if (!floored.Contains(pair.Key))
                {
                    if (pair.Value != null)
                    {
                        if (UnityEngine.Application.isPlaying) Object.Destroy(pair.Value);
                        else Object.DestroyImmediate(pair.Value);
                    }
                    retired.Add(pair.Key);
                }
            }
            for (var i = 0; i < retired.Count; i++) _lairFloorViews.Remove(retired[i]);

            if (underground == null) return;
            var baseline = TowerStructurePresenter.FloorY(0) - 0.74f;
            var groundCenter = -2.4f + (_renderedGroundSlab.MinX + _renderedGroundSlab.MaxX + 1) * 0.25f;
            if (_renderedGroundSlab.Width <= 0) groundCenter = -1.4f;
            var earthLeft = groundCenter - UndergroundDigState.GridWidthCells * GridPlacementController.UndergroundCellSize * 0.5f;
            for (var i = 0; i < underground.ExcavatedCells.Count; i++)
            {
                var cell = underground.ExcavatedCells[i];
                var x = earthLeft + (cell.X + 0.5f) * GridPlacementController.UndergroundCellSize;
                var y = baseline - (cell.Depth + 0.5f) * GridPlacementController.UndergroundCellSize;
                var view = UpdateOrCreateQuad(_groundRoot, $"Excavated Cell {cell.X}_{cell.Depth}",
                    new Color(0.035f, 0.052f, 0.061f), new Vector3(x, y, ExcavationZ), new Vector2(1.005f, 1.005f));
                _excavationViews[cell] = view;
            }

            for (var i = 0; i < underground.FlooredCells.Count; i++)
            {
                var cell = underground.FlooredCells[i];
                var x = earthLeft + (cell.X + 0.5f) * GridPlacementController.UndergroundCellSize;
                var y = baseline - (cell.Depth + 0.5f) * GridPlacementController.UndergroundCellSize;
                var floor = UpdateOrCreateQuad(_groundRoot, $"Lair Floor {cell.X}_{cell.Depth}",
                    new Color(0.11f, 0.19f, 0.22f), new Vector3(x, y, LairFloorZ), new Vector2(1.005f, 1.005f));
                UpdateOrCreateQuad(floor.transform, "Floor Slab", new Color(0.25f, 0.40f, 0.42f),
                    new Vector3(0f, -0.43f, -0.02f), new Vector2(1.005f, 0.16f));
                UpdateOrCreateQuad(floor.transform, "Floor Edge Light", new Color(0.48f, 0.79f, 0.70f),
                    new Vector3(0f, -0.34f, -0.03f), new Vector2(1.005f, 0.025f));
                _lairFloorViews[cell] = floor;
            }
        }

        private void SyncUndergroundStructures(UndergroundDigProjection underground)
        {
            var corridors = new HashSet<UndergroundCell>();
            var shaft = new HashSet<UndergroundCell>();
            var rooms = new HashSet<int>();
            if (underground != null)
            {
                for (var i = 0; i < underground.Corridors.Count; i++) corridors.Add(underground.Corridors[i]);
                for (var i = 0; i < underground.ServiceShaftCells.Count; i++) shaft.Add(underground.ServiceShaftCells[i]);
                for (var i = 0; i < underground.Rooms.Count; i++) rooms.Add(underground.Rooms[i].Id);
            }
            RetireMissingCellViews(_corridorViews, corridors);
            RetireMissingCellViews(_shaftViews, shaft);
            var retiredRooms = new List<int>();
            foreach (var pair in _undergroundRoomViews)
                if (!rooms.Contains(pair.Key)) { DestroyGenerated(pair.Value); retiredRooms.Add(pair.Key); }
            for (var i = 0; i < retiredRooms.Count; i++) _undergroundRoomViews.Remove(retiredRooms[i]);
            if (underground == null) { DestroyGenerated(_accessCoreView); _accessCoreView = null; return; }

            var baseline = TowerStructurePresenter.FloorY(0) - 0.74f;
            var groundCenter = -2.4f + (_renderedGroundSlab.MinX + _renderedGroundSlab.MaxX + 1) * 0.25f;
            if (_renderedGroundSlab.Width <= 0) groundCenter = -1.4f;
            var earthLeft = groundCenter - UndergroundDigState.GridWidthCells * GridPlacementController.UndergroundCellSize * 0.5f;

            foreach (var cell in corridors)
            {
                var x = earthLeft + cell.X + 0.5f;
                var y = baseline - cell.Depth - 0.5f;
                var view = UpdateOrCreateQuad(_groundRoot, $"Underground Corridor {cell.X}_{cell.Depth}",
                    new Color(0.17f, 0.29f, 0.32f), new Vector3(x, y, 0.30f), new Vector2(1.005f, 1.005f));
                UpdateOrCreateQuad(view.transform, "Walkway", new Color(0.37f, 0.55f, 0.52f),
                    new Vector3(0f, -0.38f, -0.015f), new Vector2(1.005f, 0.12f));
                UpdateOrCreateQuad(view.transform, "Wayfinding", new Color(0.65f, 0.79f, 0.58f),
                    new Vector3(0f, -0.25f, -0.02f), new Vector2(0.30f, 0.025f));
                _corridorViews[cell] = view;
            }

            foreach (var cell in shaft)
            {
                var x = earthLeft + cell.X + 0.5f;
                var y = baseline - cell.Depth - 0.5f;
                var view = UpdateOrCreateQuad(_groundRoot, $"Underground Shaft {cell.X}_{cell.Depth}",
                    new Color(0.08f, 0.16f, 0.20f), new Vector3(x, y, 0.26f), new Vector2(1.005f, 1.005f));
                UpdateOrCreateQuad(view.transform, "Left Rail", new Color(0.50f, 0.67f, 0.65f),
                    new Vector3(-0.27f, 0f, -0.02f), new Vector2(0.05f, 1.005f));
                UpdateOrCreateQuad(view.transform, "Right Rail", new Color(0.50f, 0.67f, 0.65f),
                    new Vector3(0.27f, 0f, -0.02f), new Vector2(0.05f, 1.005f));
                for (var rung = 0; rung < 3; rung++)
                    UpdateOrCreateQuad(view.transform, $"Rung {rung}", new Color(0.42f, 0.60f, 0.58f),
                        new Vector3(0f, -0.30f + rung * 0.30f, -0.025f), new Vector2(0.56f, 0.045f));
                _shaftViews[cell] = view;
            }

            if (underground.AccessCore.HasValue)
            {
                var cell = underground.AccessCore.Value;
                _accessCoreView = UpdateOrCreateQuad(_groundRoot, "Underground Access Core",
                    new Color(0.85f, 0.65f, 0.30f),
                    new Vector3(earthLeft + cell.X + 0.5f, baseline - cell.Depth - 0.5f, 0.23f),
                    new Vector2(0.78f, 0.09f));
            }
            else { DestroyGenerated(_accessCoreView); _accessCoreView = null; }

            for (var i = 0; i < underground.Rooms.Count; i++)
            {
                var room = underground.Rooms[i];
                var x = earthLeft + room.X + room.Width * 0.5f;
                var y = baseline - room.Depth - room.Height * 0.5f;
                var root = _groundRoot.Find($"Underground Room {room.Id}");
                if (root == null)
                {
                    root = new GameObject($"Underground Room {room.Id}").transform;
                    root.SetParent(_groundRoot, false);
                }
                root.localPosition = new Vector3(x, y, 0f);
                var color = UndergroundRoomColor(room.Type);
                UpdateOrCreateQuad(root, "Room Backdrop", color, new Vector3(0f, 0f, 0.29f),
                    new Vector2(room.Width - 0.04f, room.Height - 0.04f));
                UpdateOrCreateQuad(root, "Room Header", new Color(0.08f, 0.15f, 0.19f),
                    new Vector3(0f, room.Height * 0.5f - 0.16f, 0.25f), new Vector2(room.Width - 0.04f, 0.26f));
                UpdateOrCreateQuad(root, "Room Floor", new Color(0.42f, 0.53f, 0.52f),
                    new Vector3(0f, -room.Height * 0.5f + 0.08f, 0.24f), new Vector2(room.Width - 0.02f, 0.16f));
                UpdateOrCreateQuad(root, "Connection Status", room.IsReachable
                        ? new Color(0.40f, 0.86f, 0.56f) : new Color(1f, 0.42f, 0.34f),
                    new Vector3(room.Width * 0.5f - 0.18f, room.Height * 0.5f - 0.16f, 0.21f),
                    new Vector2(0.12f, 0.12f));
                var labelTransform = root.Find("Room Label");
                if (labelTransform == null)
                {
                    labelTransform = new GameObject("Room Label").transform;
                    labelTransform.SetParent(root, false);
                }
                labelTransform.localPosition = new Vector3(-room.Width * 0.5f + 0.15f,
                    room.Height * 0.5f - 0.08f, 0.20f);
                var label = labelTransform.GetComponent<TextMesh>();
                if (label == null) label = labelTransform.gameObject.AddComponent<TextMesh>();
                if (label != null)
                {
                    label.text = room.Type.ToString().ToUpperInvariant();
                    label.anchor = TextAnchor.UpperLeft;
                    label.characterSize = 0.04f;
                    label.fontSize = 64;
                    label.color = new Color(0.90f, 0.96f, 0.89f);
                }
                _undergroundRoomViews[room.Id] = root.gameObject;
            }
        }

        private static Color UndergroundRoomColor(UndergroundRoomType type)
        {
            var index = (int)type;
            return new Color(0.16f + (index % 3) * 0.05f,
                0.25f + (index % 4) * 0.025f,
                0.31f + (index % 5) * 0.018f);
        }

        /// <summary>Bind a bounded visible crew to stable assigned resident IDs.</summary>
        public void SyncUndergroundCrew(UndergroundOperationsProjection operations)
        {
            if (_groundRoot == null) return;
            const int maxVisibleCrew = 24;
            var visibleIds = new HashSet<int>();
            var visibleCount = 0;
            if (operations != null)
            {
                for (var i = 0; i < operations.Rooms.Count; i++)
                {
                    var room = operations.Rooms[i];
                    if (!_undergroundRoomViews.TryGetValue(room.Id, out var roomView) || roomView == null) continue;
                    var root = roomView.transform;
                    var statusTransform = root.Find("Staff Status");
                    if (statusTransform == null)
                    {
                        statusTransform = new GameObject("Staff Status").transform;
                        statusTransform.SetParent(root, false);
                    }
                    statusTransform.localPosition = new Vector3(-room.Width * 0.5f + 0.15f,
                        room.Height * 0.5f - 0.37f, 0.19f);
                    var status = statusTransform.GetComponent<TextMesh>();
                    if (status == null) status = statusTransform.gameObject.AddComponent<TextMesh>();
                    status.text = room.IsDisrupted ? $"DISRUPTED · {room.Staff}/{room.RequiredStaff} STAFF"
                        : $"{room.Staff}/{room.RequiredStaff} STAFF";
                    status.anchor = TextAnchor.UpperLeft;
                    status.characterSize = 0.04f;
                    status.fontSize = 64;
                    status.color = room.IsDisrupted ? new Color(1f, 0.52f, 0.42f)
                        : room.Staff >= room.RequiredStaff && room.IsReachable
                            ? new Color(0.60f, 0.93f, 0.67f) : new Color(0.96f, 0.77f, 0.47f);

                    var shownHere = Mathf.Min(room.AssignedResidentIds.Count, 4, maxVisibleCrew - visibleCount);
                    for (var crew = 0; crew < shownHere; crew++)
                    {
                        var residentId = room.AssignedResidentIds[crew];
                        if (!visibleIds.Add(residentId)) continue;
                        if (!_undergroundCrewViews.TryGetValue(residentId, out var skeletal) || skeletal == null)
                        {
                            var go = new GameObject($"Underground Crew {residentId}");
                            skeletal = go.AddComponent<NpcSkeletalHierarchy>();
                            skeletal.Initialize(residentId);
                            skeletal.SetCaption(null);
                            _undergroundCrewViews[residentId] = skeletal;
                        }
                        skeletal.transform.SetParent(root, false);
                        var spacing = Mathf.Min(0.72f, (room.Width - 0.6f) / Mathf.Max(1, shownHere));
                        skeletal.transform.localPosition = new Vector3((crew - (shownHere - 1) * 0.5f) * spacing,
                            -room.Height * 0.5f + 0.21f, 0.12f);
                        skeletal.SetFacing(residentId % 2 == 0 ? 1f : -1f);
                        skeletal.SetAnimationClip(room.IsDisrupted ? NpcAnimationClip.QueueWait : NpcAnimationClip.Idle);
                        visibleCount++;
                    }
                }
            }
            var retired = new List<int>();
            foreach (var pair in _undergroundCrewViews)
                if (!visibleIds.Contains(pair.Key))
                {
                    if (pair.Value != null) DestroyGenerated(pair.Value.gameObject);
                    retired.Add(pair.Key);
                }
            for (var i = 0; i < retired.Count; i++) _undergroundCrewViews.Remove(retired[i]);
        }

        public void AnimateUndergroundCrew(float time)
        {
            foreach (var crew in _undergroundCrewViews.Values)
                if (crew != null) crew.ApplyProceduralAnimation(time);
        }

        private static void RetireMissingCellViews(Dictionary<UndergroundCell, GameObject> views, HashSet<UndergroundCell> active)
        {
            var retired = new List<UndergroundCell>();
            foreach (var pair in views)
                if (!active.Contains(pair.Key)) { DestroyGenerated(pair.Value); retired.Add(pair.Key); }
            for (var i = 0; i < retired.Count; i++) views.Remove(retired[i]);
        }

        private static void DestroyGenerated(GameObject view)
        {
            if (view == null) return;
            if (UnityEngine.Application.isPlaying) Object.Destroy(view);
            else Object.DestroyImmediate(view);
        }

        private void EnsureExteriorWindows(TowerTopologyProjection topology, int floorCount)
        {
            _windowLightingEntries.Clear();

            // Left Facade Windows & Light Cones
            for (var f = 0; f < floorCount; f++)
            {
                var slab = topology != null && topology.TryGetFloorSlab(f, out var s) ? s : new CellBounds(f, -14, 16);
                var worldLeft = -2.4f + slab.MinX * 0.5f;
                var floorY = TowerStructurePresenter.FloorY(f);
                var windowX = worldLeft - 0.16f;
                var centerY = floorY + 0.03f;

                // Window Frame Header (Z = -0.05m)
                var frameObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Window Frame {f}", WindowFrameColor,
                    new Vector3(windowX, floorY + 0.46f, -0.05f),
                    new Vector2(0.24f, 0.08f));
                if (!_leftWindowFrames.Contains(frameObj)) _leftWindowFrames.Add(frameObj);

                // Window Sill (Z = -0.05m)
                var sillObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Window Sill {f}", WindowSillColor,
                    new Vector3(windowX, floorY - 0.40f, -0.05f),
                    new Vector2(0.26f, 0.06f));
                if (!_leftWindowSills.Contains(sillObj)) _leftWindowSills.Add(sillObj);

                // Recessed Window Glass (Z = 0.00m) — uses shared _worldMaterial
                var glassObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Window Glass {f}", WindowDayColor,
                    new Vector3(windowX, centerY, 0.00f),
                    new Vector2(0.20f, 0.78f));
                if (!_leftWindowGlasses.Contains(glassObj)) _leftWindowGlasses.Add(glassObj);

                // Volumetric Light Cone (Z = -0.20m, projects outward to the left, dir = -1)
                var coneObj = UpdateOrCreateLightCone(_volumetricLightRoot, $"Left Light Cone {f}",
                    new Vector3(windowX, centerY, 0f), 1.20f, -1f);
                if (!_volumetricCones.Contains(coneObj)) _volumetricCones.Add(coneObj);

                var glassRenderer = glassObj.GetComponent<MeshRenderer>();
                var coneRenderer = coneObj.GetComponent<MeshRenderer>();
                _windowLightingEntries.Add(new WindowLightingEntry(glassRenderer, coneRenderer, f, true));
            }

            // Right Facade Windows & Light Cones (Upper floors, f >= 1)
            for (var f = 1; f < floorCount; f++)
            {
                var slab = topology != null && topology.TryGetFloorSlab(f, out var s) ? s : new CellBounds(f, -14, 16);
                var worldRight = -2.4f + (slab.MaxX + 1) * 0.5f;
                var floorY = TowerStructurePresenter.FloorY(f);
                var windowX = worldRight + 0.16f;
                var centerY = floorY + 0.03f;

                // Window Frame Header (Z = -0.05m)
                var frameObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Window Frame {f}", WindowFrameColor,
                    new Vector3(windowX, floorY + 0.46f, -0.05f),
                    new Vector2(0.24f, 0.08f));
                if (!_rightWindowFrames.Contains(frameObj)) _rightWindowFrames.Add(frameObj);

                // Window Sill (Z = -0.05m)
                var sillObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Window Sill {f}", WindowSillColor,
                    new Vector3(windowX, floorY - 0.40f, -0.05f),
                    new Vector2(0.26f, 0.06f));
                if (!_rightWindowSills.Contains(sillObj)) _rightWindowSills.Add(sillObj);

                // Recessed Window Glass (Z = 0.00m) — uses shared _worldMaterial
                var glassObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Window Glass {f}", WindowDayColor,
                    new Vector3(windowX, centerY, 0.00f),
                    new Vector2(0.20f, 0.78f));
                if (!_rightWindowGlasses.Contains(glassObj)) _rightWindowGlasses.Add(glassObj);

                // Volumetric Light Cone (Z = -0.20m, projects outward to the right, dir = +1)
                var coneObj = UpdateOrCreateLightCone(_volumetricLightRoot, $"Right Light Cone {f}",
                    new Vector3(windowX, centerY, 0f), 1.20f, 1f);
                if (!_volumetricCones.Contains(coneObj)) _volumetricCones.Add(coneObj);

                var glassRenderer = glassObj.GetComponent<MeshRenderer>();
                var coneRenderer = coneObj.GetComponent<MeshRenderer>();
                _windowLightingEntries.Add(new WindowLightingEntry(glassRenderer, coneRenderer, f, false));
            }

            UpdateWindowLighting(new DayPhase(1, 12, 0, false));
        }

        private void BuildRoofline(TowerTopologyProjection topology, int floorCount, CellBounds topSlab)
        {
            var topFloor = floorCount - 1;
            var worldLeft = -2.4f + topSlab.MinX * 0.5f;
            var worldRight = -2.4f + (topSlab.MaxX + 1) * 0.5f;
            var deckY = TowerStructurePresenter.FloorY(topFloor) + 1.01f; // top of slab ceiling

            var roofLeft = worldLeft - WallThickness - CorniceOverhang;
            var roofRight = worldRight + WallThickness + CorniceOverhang;
            var roofWidth = roofRight - roofLeft;
            var roofCenter = (roofLeft + roofRight) * 0.5f;

            // 1. Structural Roof Slab
            UpdateOrCreateQuad(_rooflineRoot, "Roof Structural Slab", RoofDeckColor,
                new Vector3(roofCenter, deckY + RoofDeckThickness * 0.5f, 0.15f),
                new Vector2(roofWidth, RoofDeckThickness));

            // 2. Cornice Overhang Fascia Lip
            UpdateOrCreateQuad(_rooflineRoot, "Cornice Overhang Fascia", CorniceTrimColor,
                new Vector3(roofCenter, deckY + 0.04f, 0.12f),
                new Vector2(roofWidth + 0.08f, 0.08f));

            // 3. Roof Ballast & Gravel Deck
            var deckTopY = deckY + RoofDeckThickness;
            UpdateOrCreateQuad(_rooflineRoot, "Roof Gravel Ballast", RoofBallastColor,
                new Vector3(roofCenter, deckTopY + 0.03f, 0.16f),
                new Vector2(Mathf.Max(0.5f, roofWidth - 0.60f), 0.06f));

            // 4. Parapet Walls
            var leftParapetX = worldLeft - WallThickness + 0.06f;
            var rightParapetX = worldRight + WallThickness - 0.06f;

            UpdateOrCreateQuad(_rooflineRoot, "Left Parapet Wall", WallCoreColor,
                new Vector3(leftParapetX, deckTopY + ParapetHeight * 0.5f, 0.10f),
                new Vector2(0.24f, ParapetHeight));
            UpdateOrCreateQuad(_rooflineRoot, "Left Parapet Coping", CorniceTrimColor,
                new Vector3(leftParapetX, deckTopY + ParapetHeight + 0.04f, 0.08f),
                new Vector2(0.30f, 0.08f));

            UpdateOrCreateQuad(_rooflineRoot, "Right Parapet Wall", WallCoreColor,
                new Vector3(rightParapetX, deckTopY + ParapetHeight * 0.5f, 0.10f),
                new Vector2(0.24f, ParapetHeight));
            UpdateOrCreateQuad(_rooflineRoot, "Right Parapet Coping", CorniceTrimColor,
                new Vector3(rightParapetX, deckTopY + ParapetHeight + 0.04f, 0.08f),
                new Vector2(0.30f, 0.08f));

            // 5. Rooftop Mechanical Fixtures
            BuildRooftopFixtures(deckTopY, roofLeft, roofRight);
        }

        private void BuildRooftopFixtures(float deckTopY, float roofLeft, float roofRight)
        {
            // Elevator Penthouse Machinery Housing (-1.90m shaft center)
            const float shaftX = -1.90f;
            UpdateOrCreateQuad(_fixturesRoot, "Elevator Penthouse Housing", FixtureMetalColor,
                new Vector3(shaftX, deckTopY + 0.45f, 0.12f),
                new Vector2(1.24f, 0.90f));
            UpdateOrCreateQuad(_fixturesRoot, "Elevator Penthouse Cap", CorniceTrimColor,
                new Vector3(shaftX, deckTopY + 0.94f, 0.10f),
                new Vector2(1.36f, 0.08f));
            UpdateOrCreateQuad(_fixturesRoot, "Elevator Penthouse Louver", RoofBallastColor,
                new Vector3(shaftX + 0.28f, deckTopY + 0.50f, 0.08f),
                new Vector2(0.42f, 0.32f));

            // Rooftop HVAC Chiller Unit
            var hvacX = shaftX + 2.4f;
            if (hvacX < roofRight - 1.2f)
            {
                UpdateOrCreateQuad(_fixturesRoot, "Rooftop HVAC Chiller", FixtureMetalColor,
                    new Vector3(hvacX, deckTopY + 0.28f, 0.14f),
                    new Vector2(0.85f, 0.56f));
                UpdateOrCreateQuad(_fixturesRoot, "HVAC Fan Cowling L", RoofBallastColor,
                    new Vector3(hvacX - 0.20f, deckTopY + 0.59f, 0.11f),
                    new Vector2(0.28f, 0.08f));
                UpdateOrCreateQuad(_fixturesRoot, "HVAC Fan Cowling R", RoofBallastColor,
                    new Vector3(hvacX + 0.20f, deckTopY + 0.59f, 0.11f),
                    new Vector2(0.28f, 0.08f));
            }

            // Communications Mast & Aviation Warning Light
            var mastX = roofLeft + 1.20f;
            UpdateOrCreateQuad(_fixturesRoot, "Communications Mast", DownspoutColor,
                new Vector3(mastX, deckTopY + 1.20f, 0.14f),
                new Vector2(0.06f, 2.40f));
            UpdateOrCreateQuad(_fixturesRoot, "Mast Cross Arm", DownspoutColor,
                new Vector3(mastX, deckTopY + 1.80f, 0.13f),
                new Vector2(0.40f, 0.04f));
            UpdateOrCreateQuad(_fixturesRoot, "Aviation Warning Beacon", BeaconGlowColor,
                new Vector3(mastX, deckTopY + 2.44f, -0.45f),
                new Vector2(0.12f, 0.12f));

            // Roof Access Hatch
            var hatchX = shaftX - 1.8f;
            if (hatchX > roofLeft + 0.8f)
            {
                UpdateOrCreateQuad(_fixturesRoot, "Roof Access Hatch", FixtureMetalColor,
                    new Vector3(hatchX, deckTopY + 0.22f, 0.14f),
                    new Vector2(0.55f, 0.44f));
            }
        }

        private void BuildSetbackTerraces(TowerTopologyProjection topology, int floorCount)
        {
            if (topology == null || floorCount <= 1) return;

            for (var f = 0; f < floorCount - 1; f++)
            {
                if (!topology.TryGetFloorSlab(f, out var lower) || !topology.TryGetFloorSlab(f + 1, out var upper)) continue;

                // Right-side Stepback
                if (lower.MaxX > upper.MaxX)
                {
                    var upperRight = -2.4f + (upper.MaxX + 1) * 0.5f;
                    var lowerRight = -2.4f + (lower.MaxX + 1) * 0.5f + WallThickness;
                    var terraceWidth = lowerRight - upperRight;
                    var terraceCenter = (upperRight + lowerRight) * 0.5f;
                    var terraceY = TowerStructurePresenter.FloorY(f + 1) - 0.74f;

                    UpdateOrCreateQuad(_terracesRoot, $"Terrace Slab R {f}", RoofDeckColor,
                        new Vector3(terraceCenter, terraceY + 0.08f, 0.15f),
                        new Vector2(terraceWidth, 0.16f));
                    UpdateOrCreateQuad(_terracesRoot, $"Terrace Railing R {f}", CorniceTrimColor,
                        new Vector3(terraceCenter, terraceY + 0.36f, 0.12f),
                        new Vector2(terraceWidth, 0.38f));
                }

                // Left-side Stepback
                if (lower.MinX < upper.MinX)
                {
                    var lowerLeft = -2.4f + lower.MinX * 0.5f - WallThickness;
                    var upperLeft = -2.4f + upper.MinX * 0.5f;
                    var terraceWidth = upperLeft - lowerLeft;
                    var terraceCenter = (lowerLeft + upperLeft) * 0.5f;
                    var terraceY = TowerStructurePresenter.FloorY(f + 1) - 0.74f;

                    UpdateOrCreateQuad(_terracesRoot, $"Terrace Slab L {f}", RoofDeckColor,
                        new Vector3(terraceCenter, terraceY + 0.08f, 0.15f),
                        new Vector2(terraceWidth, 0.16f));
                    UpdateOrCreateQuad(_terracesRoot, $"Terrace Railing L {f}", CorniceTrimColor,
                        new Vector3(terraceCenter, terraceY + 0.36f, 0.12f),
                        new Vector2(terraceWidth, 0.38f));
                }
            }
        }

        private void CalculateStageBounds(int floorCount, CellBounds ground, CellBounds top)
        {
            var groundLeft = -2.4f + ground.MinX * 0.5f - WallThickness;
            var groundRight = -2.4f + (ground.MaxX + 1) * 0.5f + WallThickness;
            var topFloorY = TowerStructurePresenter.FloorY(floorCount - 1) + 1.01f + RoofDeckThickness + ParapetHeight;
            var streetY = TowerStructurePresenter.FloorY(0) - 0.74f;

            var leftZone = new Bounds(
                new Vector3(groundLeft - 6.0f, (streetY + topFloorY) * 0.5f, 0f),
                new Vector3(12.0f, topFloorY - streetY + 10.0f, 10.0f));

            var rightZone = new Bounds(
                new Vector3(groundRight + 8.0f, (streetY + topFloorY) * 0.5f, 0f),
                new Vector3(16.0f, topFloorY - streetY + 10.0f, 10.0f));

            var rooftopZone = new Bounds(
                new Vector3((groundLeft + groundRight) * 0.5f, topFloorY + 4.0f, 0f),
                new Vector3(groundRight - groundLeft + 4.0f, 8.0f, 10.0f));

            var interiorEnclosure = new Bounds(
                new Vector3((groundLeft + groundRight) * 0.5f, (streetY + topFloorY) * 0.5f, 0.5f),
                new Vector3(groundRight - groundLeft, topFloorY - streetY, 2.0f));

            _stageBounds = new OutsideStageBounds(
                leftZone, rightZone, rooftopZone, interiorEnclosure,
                new Vector2(groundLeft, topFloorY), new Vector2(groundRight, topFloorY), topFloorY);
        }

        public void UpdateLighting(DayPhase phase)
        {
            UpdateAviationBeacons(phase);
            UpdateWindowLighting(phase);
        }

        private void UpdateAviationBeacons(DayPhase phase)
        {
            if (_fixturesRoot == null) return;
            // Beacon light pulses at night and dims by day
            var hour = phase.Hour + phase.Minute / 60f;
            var night = hour < 6f ? 1f : hour >= 18f ? 1f : 0f;
            var beacon = _fixturesRoot.Find("Aviation Warning Beacon");
            if (beacon != null)
            {
                var renderer = beacon.GetComponent<MeshRenderer>();
                if (renderer != null)
                {
                    var pulse = 0.5f + 0.5f * Mathf.Sin(Time.time * 4f);
                    var alpha = Mathf.Lerp(0.2f, 1.0f, night * pulse);
                    var col = new Color(BeaconGlowColor.r, BeaconGlowColor.g, BeaconGlowColor.b, alpha);
                    SetColor(renderer, col);
                }
            }
        }

        public void UpdateWindowLighting(DayPhase phase)
        {
            var hour = phase.Hour + phase.Minute / 60f;
            // Smooth continuous night factor: 1.0 fully at night, 0.0 fully by day.
            // Dawn ramp: 5.5h (full night) → 6.5h (full day). Dusk ramp: 19.5h → 20.5h.
            float smoothNight;
            if (hour < 5.5f || hour >= 20.5f)
                smoothNight = 1f;
            else if (hour < 6.5f)
                smoothNight = 6.5f - hour;          // 1.0 at 5.5h → 0.0 at 6.5h
            else if (hour < 19.5f)
                smoothNight = 0f;
            else
                smoothNight = hour - 19.5f;         // 0.0 at 19.5h → 1.0 at 20.5h

            for (var i = 0; i < _windowLightingEntries.Count; i++)
            {
                var entry = _windowLightingEntries[i];
                var isOccupied = entry.IsLeft
                    ? ((entry.Floor * 7 + 3) % 5 != 0)
                    : ((entry.Floor * 13 + 2) % 5 != 0);

                if (entry.GlassRenderer != null)
                {
                    var targetNightGlass = isOccupied ? WindowNightLitColor : WindowNightDarkColor;
                    var currentGlassColor = Color.Lerp(WindowDayColor, targetNightGlass, smoothNight);
                    SetColor(entry.GlassRenderer, currentGlassColor);
                }

                if (entry.ConeRenderer != null)
                {
                    var targetNightCone = isOccupied ? ConeNightLitColor : ConeNightDarkColor;
                    var currentConeColor = Color.Lerp(ConeDayColor, targetNightCone, smoothNight);
                    SetColor(entry.ConeRenderer, currentConeColor);
                }
            }
        }

        public void Clear()
        {
            if (_root != null)
            {
                if (UnityEngine.Application.isPlaying) Object.Destroy(_root.gameObject);
                else Object.DestroyImmediate(_root.gameObject);
            }

            for (var i = 0; i < _coneMeshes.Count; i++)
            {
                var m = _coneMeshes[i];
                if (m != null)
                {
                    if (UnityEngine.Application.isPlaying) Object.Destroy(m);
                    else Object.DestroyImmediate(m);
                }
            }
            _coneMeshes.Clear();

            _root = null;
            _leftFacadeRoot = null;
            _rightFacadeRoot = null;
            _rooflineRoot = null;
            _fixturesRoot = null;
            _terracesRoot = null;
            _volumetricLightRoot = null;
            _groundRoot = null;
            _excavationViews.Clear();
            _lairFloorViews.Clear();
            _corridorViews.Clear();
            _shaftViews.Clear();
            _undergroundRoomViews.Clear();
            _undergroundCrewViews.Clear();
            _accessCoreView = null;
            _renderedUndergroundRevision = -1;

            _leftWallSlices.Clear();
            _rightWallSlices.Clear();
            _leftSpandrels.Clear();
            _rightSpandrels.Clear();
            _leftWindowFrames.Clear();
            _leftWindowGlasses.Clear();
            _leftWindowSills.Clear();
            _rightWindowFrames.Clear();
            _rightWindowGlasses.Clear();
            _rightWindowSills.Clear();
            _volumetricCones.Clear();
            _windowLightingEntries.Clear();
            _terraceObjects.Clear();
            _roofObjects.Clear();
            _renderedFloorCount = -1;
        }

        public void Dispose()
        {
            Clear();
            if (_coneMaterial != null)
            {
                if (UnityEngine.Application.isPlaying) Object.Destroy(_coneMaterial);
                else Object.DestroyImmediate(_coneMaterial);
                _coneMaterial = null;
            }
        }

        private GameObject UpdateOrCreateQuad(Transform parent, string name, Color color, Vector3 pos, Vector2 size, Material mat = null)
        {
            var child = parent.Find(name);
            GameObject go;
            MeshRenderer renderer;
            var targetMat = mat ?? _worldMaterial;
            if (child == null)
            {
                go = GameObject.CreatePrimitive(PrimitiveType.Quad);
                go.name = name;
                go.transform.SetParent(parent, false);
                var col = go.GetComponent<Collider>();
                if (col != null)
                {
                    if (UnityEngine.Application.isPlaying) Object.Destroy(col);
                    else Object.DestroyImmediate(col);
                }
                renderer = go.GetComponent<MeshRenderer>();
                renderer.sharedMaterial = targetMat;
            }
            else
            {
                go = child.gameObject;
                renderer = go.GetComponent<MeshRenderer>();
                if (targetMat != null) renderer.sharedMaterial = targetMat;
            }

            go.transform.localPosition = pos;
            go.transform.localScale = new Vector3(size.x, size.y, 1f);
            SetColor(renderer, color);
            return go;
        }

        private GameObject UpdateOrCreateLightCone(
            Transform parent, string name, Vector3 origin, float length, float direction)
        {
            if (parent == null) return null;
            var child = parent.Find(name);
            GameObject go;
            MeshFilter filter;
            MeshRenderer renderer;
            Mesh mesh;

            if (child == null)
            {
                go = new GameObject(name);
                go.transform.SetParent(parent, false);
                filter = go.AddComponent<MeshFilter>();
                renderer = go.AddComponent<MeshRenderer>();
                mesh = CreateLightConeMesh(origin, length, direction, name);
                filter.sharedMesh = mesh;
                _coneMeshes.Add(mesh);
            }
            else
            {
                go = child.gameObject;
                filter = go.GetComponent<MeshFilter>();
                if (filter == null) filter = go.AddComponent<MeshFilter>();
                renderer = go.GetComponent<MeshRenderer>();
                if (renderer == null) renderer = go.AddComponent<MeshRenderer>();

                mesh = filter.sharedMesh;
                if (mesh == null)
                {
                    mesh = CreateLightConeMesh(origin, length, direction, name);
                    filter.sharedMesh = mesh;
                    _coneMeshes.Add(mesh);
                }
                else
                {
                    UpdateLightConeMesh(mesh, origin, length, direction);
                }
            }

            go.transform.localPosition = new Vector3(0f, 0f, -0.20f);
            if (_coneMaterial != null) renderer.sharedMaterial = _coneMaterial;
            SetColor(renderer, ConeDayColor);

            return go;
        }

        private static Mesh CreateLightConeMesh(Vector3 origin, float length, float direction, string name)
        {
            var mesh = new Mesh { name = name };
            UpdateLightConeMesh(mesh, origin, length, direction);
            return mesh;
        }

        private static void UpdateLightConeMesh(Mesh mesh, Vector3 origin, float length, float direction)
        {
            var v0 = new Vector3(origin.x, origin.y + 0.35f, 0f);
            var v1 = new Vector3(origin.x + direction * length, origin.y + 0.60f, 0f);
            var v2 = new Vector3(origin.x + direction * length, origin.y - 0.70f, 0f);
            var v3 = new Vector3(origin.x, origin.y - 0.35f, 0f);

            mesh.vertices = new[] { v0, v1, v2, v3 };
            mesh.triangles = new[]
            {
                0, 1, 2,
                0, 2, 3,
                0, 2, 1,
                0, 3, 2
            };
            mesh.colors = new[]
            {
                new Color(1f, 1f, 1f, 1f),
                new Color(1f, 1f, 1f, 0f),
                new Color(1f, 1f, 1f, 0f),
                new Color(1f, 1f, 1f, 1f)
            };
            mesh.uv = new[]
            {
                new Vector2(0f, 1f),
                new Vector2(1f, 1f),
                new Vector2(1f, 0f),
                new Vector2(0f, 0f)
            };
            mesh.RecalculateBounds();
        }


        private void SetColor(MeshRenderer renderer, Color color)
        {
            if (renderer == null) return;
            var material = renderer.sharedMaterial == _coneMaterial ? _coneMaterial : _worldMaterial;
            if (material != null && renderer.sharedMaterial != material)
                renderer.sharedMaterial = material;
            if (_colorBlock == null) _colorBlock = new MaterialPropertyBlock();
            renderer.GetPropertyBlock(_colorBlock);
            _colorBlock.SetColor("_BaseColor", color);
            _colorBlock.SetColor("_Color", color);
            renderer.SetPropertyBlock(_colorBlock);
        }
    }

    /// <summary>
    /// Immutable stage boundaries defining exterior atmospheric space and interior cutaway enclosure.
    /// </summary>
    public readonly struct OutsideStageBounds
    {
        public OutsideStageBounds(
            Bounds leftZone, Bounds rightZone, Bounds rooftopZone, Bounds interiorEnclosure,
            Vector2 leftScupper, Vector2 rightScupper, float roofDeckY)
        {
            LeftExteriorZone = leftZone;
            RightExteriorZone = rightZone;
            RooftopZone = rooftopZone;
            InteriorCutawayEnclosure = interiorEnclosure;
            LeftScupper = leftScupper;
            RightScupper = rightScupper;
            RoofDeckY = roofDeckY;
        }

        public Bounds LeftExteriorZone { get; }
        public Bounds RightExteriorZone { get; }
        public Bounds RooftopZone { get; }
        public Bounds InteriorCutawayEnclosure { get; }
        public Vector2 LeftScupper { get; }
        public Vector2 RightScupper { get; }
        public float RoofDeckY { get; }
    }
}
