using System;
using System.Collections.Generic;
using OneRoof.Application.Tower;
using OneRoof.Domain.Time;
using OneRoof.Domain.Topology;
using UnityEngine;
using Object = UnityEngine.Object;

namespace OneRoof.Presentation.Tower
{
    /// <summary>
    /// Deep presenter responsible for the autogenerated building exterior envelope,
    /// vertical facade cutaways, ground lobby entrance canopy, roof deck, parapets,
    /// mechanical fixtures (penthouse, HVAC, antenna), and the outside weather stage.
    /// Pure presentation layer: consumes TowerTopologyProjection with 0 domain mutations.
    /// </summary>
    public sealed class BuildingExteriorPresenter
    {
        public const float WallThickness = 0.36f;
        public const float CladdingThickness = 0.08f;
        public const float SpandrelProtrusion = 0.06f;
        public const float CorniceOverhang = 0.18f;
        public const float RoofDeckThickness = 0.28f;
        public const float ParapetHeight = 0.42f;

        private Transform _parent;
        private Material _worldMaterial;
        private MaterialPropertyBlock _colorBlock;

        private Transform _root;
        private Transform _leftFacadeRoot;
        private Transform _rightFacadeRoot;
        private Transform _rooflineRoot;
        private Transform _fixturesRoot;
        private Transform _terracesRoot;
        private Transform _volumetricLightRoot;

        private readonly List<GameObject> _leftWallSlices = new List<GameObject>();
        private readonly List<GameObject> _rightWallSlices = new List<GameObject>();
        private readonly List<GameObject> _leftSpandrels = new List<GameObject>();
        private readonly List<GameObject> _rightSpandrels = new List<GameObject>();
        private readonly List<GameObject> _terraceObjects = new List<GameObject>();
        private readonly List<GameObject> _roofObjects = new List<GameObject>();

        private readonly List<GameObject> _leftWindowFrames = new List<GameObject>();
        private readonly List<GameObject> _leftWindowGlasses = new List<GameObject>();
        private readonly List<GameObject> _leftWindowSills = new List<GameObject>();
        private readonly List<GameObject> _rightWindowFrames = new List<GameObject>();
        private readonly List<GameObject> _rightWindowGlasses = new List<GameObject>();
        private readonly List<GameObject> _rightWindowSills = new List<GameObject>();
        private readonly List<GameObject> _volumetricCones = new List<GameObject>();
        private readonly List<Mesh> _coneMeshes = new List<Mesh>();
        private readonly List<WindowLightingEntry> _windowLightingEntries = new List<WindowLightingEntry>();

        private int _renderedFloorCount = -1;
        private CellBounds _renderedGroundSlab;
        private CellBounds _renderedTopSlab;
        private OutsideStageBounds _stageBounds;

        public OutsideStageBounds StageBounds => _stageBounds;
        public int RenderedFloorCount => _renderedFloorCount;
        public Transform Root => _root;
        public Transform VolumetricLightRoot => _volumetricLightRoot;

        public IReadOnlyList<GameObject> LeftWindowFrames => _leftWindowFrames;
        public IReadOnlyList<GameObject> LeftWindowGlasses => _leftWindowGlasses;
        public IReadOnlyList<GameObject> LeftWindowSills => _leftWindowSills;
        public IReadOnlyList<GameObject> RightWindowFrames => _rightWindowFrames;
        public IReadOnlyList<GameObject> RightWindowGlasses => _rightWindowGlasses;
        public IReadOnlyList<GameObject> RightWindowSills => _rightWindowSills;
        public IReadOnlyList<GameObject> VolumetricCones => _volumetricCones;

        // Palette
        private static readonly Color WallCoreColor = new Color(0.18f, 0.22f, 0.28f);
        private static readonly Color CladdingColor = new Color(0.32f, 0.40f, 0.50f);
        private static readonly Color SpandrelColor = new Color(0.28f, 0.35f, 0.44f);
        private static readonly Color PlinthColor = new Color(0.12f, 0.15f, 0.19f);
        private static readonly Color RoofDeckColor = new Color(0.22f, 0.28f, 0.36f);
        private static readonly Color RoofBallastColor = new Color(0.13f, 0.16f, 0.22f);
        private static readonly Color CorniceTrimColor = new Color(0.38f, 0.46f, 0.58f);
        private static readonly Color CanopyColor = new Color(0.24f, 0.32f, 0.40f);
        private static readonly Color DownspoutColor = new Color(0.20f, 0.26f, 0.32f);
        private static readonly Color FixtureMetalColor = new Color(0.30f, 0.38f, 0.46f);
        private static readonly Color BeaconGlowColor = new Color(1.0f, 0.25f, 0.15f);

        public static readonly Color WindowFrameColor = new Color(0.24f, 0.30f, 0.38f);
        public static readonly Color WindowSillColor = new Color(0.34f, 0.42f, 0.52f);
        public static readonly Color WindowDayColor = new Color(0.35f, 0.52f, 0.65f, 0.70f);
        public static readonly Color WindowNightLitColor = new Color(1.00f, 0.74f, 0.38f, 0.95f);
        public static readonly Color WindowNightDarkColor = new Color(0.12f, 0.15f, 0.20f, 0.75f);
        public static readonly Color ConeDayColor = new Color(0.92f, 0.96f, 1.0f, 0.20f);
        public static readonly Color ConeNightLitColor = new Color(1.00f, 0.78f, 0.38f, 0.32f);
        public static readonly Color ConeNightDarkColor = new Color(0f, 0f, 0f, 0f);

        private readonly struct WindowLightingEntry
        {
            public readonly MeshRenderer GlassRenderer;
            public readonly MeshRenderer ConeRenderer;
            public readonly int Floor;
            public readonly bool IsLeft;

            public WindowLightingEntry(MeshRenderer glassRenderer, MeshRenderer coneRenderer, int floor, bool isLeft)
            {
                GlassRenderer = glassRenderer;
                ConeRenderer = coneRenderer;
                Floor = floor;
                IsLeft = isLeft;
            }
        }

        public void Initialize(Transform parent, Material worldMaterial, MaterialPropertyBlock colorBlock)
        {
            _parent = parent;
            _worldMaterial = worldMaterial;
            _colorBlock = colorBlock ?? new MaterialPropertyBlock();

            // Configure the shared world material for alpha-blended transparent rendering.
            // This allows cone geometry (vertex alpha = 0 at tips) to fade out correctly
            // while all structural quads (alpha = 1) appear fully opaque.
            if (_worldMaterial != null)
            {
                _worldMaterial.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
                _worldMaterial.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
                _worldMaterial.SetInt("_ZWrite", 0);
                _worldMaterial.renderQueue = (int)UnityEngine.Rendering.RenderQueue.Transparent;
                _worldMaterial.SetOverrideTag("RenderType", "Transparent");
            }

            Clear();
        }

        public void EnsureExteriorViews(TowerTopologyProjection topology)
        {
            if (_parent == null || _worldMaterial == null) return;
            var floorCount = topology != null ? topology.FloorCount : TowerStructurePresenter.InitialFloorCount;
            if (floorCount <= 0) return;

            CellBounds groundSlab = default;
            CellBounds topSlab = default;
            if (topology != null)
            {
                topology.TryGetFloorSlab(0, out groundSlab);
                topology.TryGetFloorSlab(floorCount - 1, out topSlab);
            }
            else
            {
                groundSlab = new CellBounds(0, -14, 16);
                topSlab = new CellBounds(floorCount - 1, -14, 16);
            }

            if (_root != null && _renderedFloorCount == floorCount &&
                _renderedGroundSlab.Equals(groundSlab) && _renderedTopSlab.Equals(topSlab))
            {
                return;
            }

            EnsureHierarchyRoots();
            _renderedFloorCount = floorCount;
            _renderedGroundSlab = groundSlab;
            _renderedTopSlab = topSlab;

            BuildFacades(topology, floorCount);
            EnsureExteriorWindows(topology, floorCount);
            BuildRoofline(topology, floorCount, topSlab);
            BuildSetbackTerraces(topology, floorCount);
            CalculateStageBounds(floorCount, groundSlab, topSlab);
        }

        private void EnsureHierarchyRoots()
        {
            if (_root != null) return;

            var existing = _parent.Find("Building Exterior Envelope");
            if (existing != null)
            {
                _root = existing;
            }
            else
            {
                _root = new GameObject("Building Exterior Envelope").transform;
                _root.SetParent(_parent, false);
            }

            _leftFacadeRoot = EnsureChildTransform(_root, "Left Facade");
            _rightFacadeRoot = EnsureChildTransform(_root, "Right Facade");
            _rooflineRoot = EnsureChildTransform(_root, "Roofline & Capping");
            _fixturesRoot = EnsureChildTransform(_rooflineRoot, "Rooftop Fixtures");
            _terracesRoot = EnsureChildTransform(_root, "Setback Terraces");
            _volumetricLightRoot = EnsureChildTransform(_root, "Exterior Volumetric Lighting");
        }

        private static Transform EnsureChildTransform(Transform parent, string name)
        {
            var child = parent.Find(name);
            if (child != null) return child;
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);
            return go.transform;
        }

        private void BuildFacades(TowerTopologyProjection topology, int floorCount)
        {
            // 1. Foundation Plinth (Left side)
            var ground = topology != null && topology.TryGetFloorSlab(0, out var g) ? g : new CellBounds(0, -14, 16);
            var groundLeft = -2.4f + ground.MinX * 0.5f;
            var groundBaseline = TowerStructurePresenter.FloorY(0) - 0.74f;

            UpdateOrCreateQuad(_leftFacadeRoot, "Left Foundation Plinth", PlinthColor,
                new Vector3(groundLeft - WallThickness * 0.5f - 0.04f, groundBaseline - 0.24f, 0.10f),
                new Vector2(WallThickness + 0.08f, 0.48f));

            // Downspout Left
            var topFloorY = TowerStructurePresenter.FloorY(floorCount - 1) + 1.01f;
            var downspoutHeight = topFloorY - groundBaseline + 0.48f;
            var downspoutCenterY = (groundBaseline - 0.48f + topFloorY) * 0.5f;
            UpdateOrCreateQuad(_leftFacadeRoot, "Left Downspout", DownspoutColor,
                new Vector3(groundLeft - WallThickness - 0.02f, downspoutCenterY, -0.05f),
                new Vector2(0.04f, downspoutHeight));

            // Per-Floor Left Wall Slices & Spandrels
            for (var f = 0; f < floorCount; f++)
            {
                var slab = topology != null && topology.TryGetFloorSlab(f, out var s) ? s : new CellBounds(f, -14, 16);
                var worldLeft = -2.4f + slab.MinX * 0.5f;
                var floorY = TowerStructurePresenter.FloorY(f);
                var baselineY = floorY - 0.74f;

                // Wall Section
                var wallObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Wall {f}", WallCoreColor,
                    new Vector3(worldLeft - WallThickness * 0.5f, floorY, 0.10f),
                    new Vector2(WallThickness, 1.75f));
                if (!_leftWallSlices.Contains(wallObj)) _leftWallSlices.Add(wallObj);

                // Outer Weather Trim
                UpdateOrCreateQuad(_leftFacadeRoot, $"Left Cladding {f}", CladdingColor,
                    new Vector3(worldLeft - WallThickness + CladdingThickness * 0.5f, floorY, -0.04f),
                    new Vector2(CladdingThickness, 1.75f));

                // Horizontal Spandrel Plate
                var spandrelObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Spandrel {f}", SpandrelColor,
                    new Vector3(worldLeft - (WallThickness + SpandrelProtrusion) * 0.5f, baselineY, 0.08f),
                    new Vector2(WallThickness + SpandrelProtrusion, 0.18f));
                if (!_leftSpandrels.Contains(spandrelObj)) _leftSpandrels.Add(spandrelObj);
            }

            // Right Facade
            // Floor 0 Lobby Entrance Threshold & Cantilever Awning
            var groundRight = -2.4f + (ground.MaxX + 1) * 0.5f;
            UpdateOrCreateQuad(_rightFacadeRoot, "Lobby Entrance Portal Frame", CladdingColor,
                new Vector3(groundRight - 0.05f, TowerStructurePresenter.FloorY(0), 0.10f),
                new Vector2(0.10f, 1.55f));

            UpdateOrCreateQuad(_rightFacadeRoot, "Lobby Cantilever Canopy", CanopyColor,
                new Vector3(groundRight + 0.65f, groundBaseline + 1.28f, 0.38f),
                new Vector2(1.40f, 0.14f));

            // Upper Floor Right Wall Slices
            for (var f = 1; f < floorCount; f++)
            {
                var slab = topology != null && topology.TryGetFloorSlab(f, out var s) ? s : new CellBounds(f, -14, 16);
                var worldRight = -2.4f + (slab.MaxX + 1) * 0.5f;
                var floorY = TowerStructurePresenter.FloorY(f);
                var baselineY = floorY - 0.74f;

                var wallObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Wall {f}", WallCoreColor,
                    new Vector3(worldRight + WallThickness * 0.5f, floorY, 0.10f),
                    new Vector2(WallThickness, 1.75f));
                if (!_rightWallSlices.Contains(wallObj)) _rightWallSlices.Add(wallObj);

                UpdateOrCreateQuad(_rightFacadeRoot, $"Right Cladding {f}", CladdingColor,
                    new Vector3(worldRight + WallThickness - CladdingThickness * 0.5f, floorY, -0.04f),
                    new Vector2(CladdingThickness, 1.75f));

                var spandrelObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Spandrel {f}", SpandrelColor,
                    new Vector3(worldRight + (WallThickness + SpandrelProtrusion) * 0.5f, baselineY, 0.08f),
                    new Vector2(WallThickness + SpandrelProtrusion, 0.18f));
                if (!_rightSpandrels.Contains(spandrelObj)) _rightSpandrels.Add(spandrelObj);
            }

            // Downspout Right (from Floor 1 to Ground Canopy)
            if (floorCount > 1)
            {
                var f1Slab = topology != null && topology.TryGetFloorSlab(1, out var s1) ? s1 : new CellBounds(1, -14, 16);
                var f1Right = -2.4f + (f1Slab.MaxX + 1) * 0.5f;
                var downHeightR = topFloorY - (TowerStructurePresenter.FloorY(1) - 0.74f);
                var downCenterR = ((TowerStructurePresenter.FloorY(1) - 0.74f) + topFloorY) * 0.5f;
                UpdateOrCreateQuad(_rightFacadeRoot, "Right Downspout", DownspoutColor,
                    new Vector3(f1Right + WallThickness + 0.02f, downCenterR, -0.05f),
                    new Vector2(0.04f, downHeightR));
            }
        }

        private void EnsureExteriorWindows(TowerTopologyProjection topology, int floorCount)
        {
            _windowLightingEntries.Clear();

            // Left Facade Windows & Light Cones
            for (var f = 0; f < floorCount; f++)
            {
                var slab = topology != null && topology.TryGetFloorSlab(f, out var s) ? s : new CellBounds(f, -14, 16);
                var worldLeft = -2.4f + slab.MinX * 0.5f;
                var floorY = TowerStructurePresenter.FloorY(f);
                var windowX = worldLeft - 0.16f;
                var centerY = floorY + 0.03f;

                // Window Frame Header (Z = -0.05m)
                var frameObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Window Frame {f}", WindowFrameColor,
                    new Vector3(windowX, floorY + 0.46f, -0.05f),
                    new Vector2(0.24f, 0.08f));
                if (!_leftWindowFrames.Contains(frameObj)) _leftWindowFrames.Add(frameObj);

                // Window Sill (Z = -0.05m)
                var sillObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Window Sill {f}", WindowSillColor,
                    new Vector3(windowX, floorY - 0.40f, -0.05f),
                    new Vector2(0.26f, 0.06f));
                if (!_leftWindowSills.Contains(sillObj)) _leftWindowSills.Add(sillObj);

                // Recessed Window Glass (Z = 0.00m) — uses shared _worldMaterial
                var glassObj = UpdateOrCreateQuad(_leftFacadeRoot, $"Left Window Glass {f}", WindowDayColor,
                    new Vector3(windowX, centerY, 0.00f),
                    new Vector2(0.20f, 0.78f));
                if (!_leftWindowGlasses.Contains(glassObj)) _leftWindowGlasses.Add(glassObj);

                // Volumetric Light Cone (Z = -0.20m, projects outward to the left, dir = -1)
                var coneObj = UpdateOrCreateLightCone(_volumetricLightRoot, $"Left Light Cone {f}",
                    new Vector3(windowX, centerY, 0f), 1.20f, -1f);
                if (!_volumetricCones.Contains(coneObj)) _volumetricCones.Add(coneObj);

                var glassRenderer = glassObj.GetComponent<MeshRenderer>();
                var coneRenderer = coneObj.GetComponent<MeshRenderer>();
                _windowLightingEntries.Add(new WindowLightingEntry(glassRenderer, coneRenderer, f, true));
            }

            // Right Facade Windows & Light Cones (Upper floors, f >= 1)
            for (var f = 1; f < floorCount; f++)
            {
                var slab = topology != null && topology.TryGetFloorSlab(f, out var s) ? s : new CellBounds(f, -14, 16);
                var worldRight = -2.4f + (slab.MaxX + 1) * 0.5f;
                var floorY = TowerStructurePresenter.FloorY(f);
                var windowX = worldRight + 0.16f;
                var centerY = floorY + 0.03f;

                // Window Frame Header (Z = -0.05m)
                var frameObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Window Frame {f}", WindowFrameColor,
                    new Vector3(windowX, floorY + 0.46f, -0.05f),
                    new Vector2(0.24f, 0.08f));
                if (!_rightWindowFrames.Contains(frameObj)) _rightWindowFrames.Add(frameObj);

                // Window Sill (Z = -0.05m)
                var sillObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Window Sill {f}", WindowSillColor,
                    new Vector3(windowX, floorY - 0.40f, -0.05f),
                    new Vector2(0.26f, 0.06f));
                if (!_rightWindowSills.Contains(sillObj)) _rightWindowSills.Add(sillObj);

                // Recessed Window Glass (Z = 0.00m) — uses shared _worldMaterial
                var glassObj = UpdateOrCreateQuad(_rightFacadeRoot, $"Right Window Glass {f}", WindowDayColor,
                    new Vector3(windowX, centerY, 0.00f),
                    new Vector2(0.20f, 0.78f));
                if (!_rightWindowGlasses.Contains(glassObj)) _rightWindowGlasses.Add(glassObj);

                // Volumetric Light Cone (Z = -0.20m, projects outward to the right, dir = +1)
                var coneObj = UpdateOrCreateLightCone(_volumetricLightRoot, $"Right Light Cone {f}",
                    new Vector3(windowX, centerY, 0f), 1.20f, 1f);
                if (!_volumetricCones.Contains(coneObj)) _volumetricCones.Add(coneObj);

                var glassRenderer = glassObj.GetComponent<MeshRenderer>();
                var coneRenderer = coneObj.GetComponent<MeshRenderer>();
                _windowLightingEntries.Add(new WindowLightingEntry(glassRenderer, coneRenderer, f, false));
            }

            UpdateWindowLighting(new DayPhase(1, 12, 0, false));
        }

        private void BuildRoofline(TowerTopologyProjection topology, int floorCount, CellBounds topSlab)
        {
            var topFloor = floorCount - 1;
            var worldLeft = -2.4f + topSlab.MinX * 0.5f;
            var worldRight = -2.4f + (topSlab.MaxX + 1) * 0.5f;
            var deckY = TowerStructurePresenter.FloorY(topFloor) + 1.01f; // top of slab ceiling

            var roofLeft = worldLeft - WallThickness - CorniceOverhang;
            var roofRight = worldRight + WallThickness + CorniceOverhang;
            var roofWidth = roofRight - roofLeft;
            var roofCenter = (roofLeft + roofRight) * 0.5f;

            // 1. Structural Roof Slab
            UpdateOrCreateQuad(_rooflineRoot, "Roof Structural Slab", RoofDeckColor,
                new Vector3(roofCenter, deckY + RoofDeckThickness * 0.5f, 0.15f),
                new Vector2(roofWidth, RoofDeckThickness));

            // 2. Cornice Overhang Fascia Lip
            UpdateOrCreateQuad(_rooflineRoot, "Cornice Overhang Fascia", CorniceTrimColor,
                new Vector3(roofCenter, deckY + 0.04f, 0.12f),
                new Vector2(roofWidth + 0.08f, 0.08f));

            // 3. Roof Ballast & Gravel Deck
            var deckTopY = deckY + RoofDeckThickness;
            UpdateOrCreateQuad(_rooflineRoot, "Roof Gravel Ballast", RoofBallastColor,
                new Vector3(roofCenter, deckTopY + 0.03f, 0.16f),
                new Vector2(Mathf.Max(0.5f, roofWidth - 0.60f), 0.06f));

            // 4. Parapet Walls
            var leftParapetX = worldLeft - WallThickness + 0.06f;
            var rightParapetX = worldRight + WallThickness - 0.06f;

            UpdateOrCreateQuad(_rooflineRoot, "Left Parapet Wall", WallCoreColor,
                new Vector3(leftParapetX, deckTopY + ParapetHeight * 0.5f, 0.10f),
                new Vector2(0.24f, ParapetHeight));
            UpdateOrCreateQuad(_rooflineRoot, "Left Parapet Coping", CorniceTrimColor,
                new Vector3(leftParapetX, deckTopY + ParapetHeight + 0.04f, 0.08f),
                new Vector2(0.30f, 0.08f));

            UpdateOrCreateQuad(_rooflineRoot, "Right Parapet Wall", WallCoreColor,
                new Vector3(rightParapetX, deckTopY + ParapetHeight * 0.5f, 0.10f),
                new Vector2(0.24f, ParapetHeight));
            UpdateOrCreateQuad(_rooflineRoot, "Right Parapet Coping", CorniceTrimColor,
                new Vector3(rightParapetX, deckTopY + ParapetHeight + 0.04f, 0.08f),
                new Vector2(0.30f, 0.08f));

            // 5. Rooftop Mechanical Fixtures
            BuildRooftopFixtures(deckTopY, roofLeft, roofRight);
        }

        private void BuildRooftopFixtures(float deckTopY, float roofLeft, float roofRight)
        {
            // Elevator Penthouse Machinery Housing (-1.90m shaft center)
            const float shaftX = -1.90f;
            UpdateOrCreateQuad(_fixturesRoot, "Elevator Penthouse Housing", FixtureMetalColor,
                new Vector3(shaftX, deckTopY + 0.45f, 0.12f),
                new Vector2(1.24f, 0.90f));
            UpdateOrCreateQuad(_fixturesRoot, "Elevator Penthouse Cap", CorniceTrimColor,
                new Vector3(shaftX, deckTopY + 0.94f, 0.10f),
                new Vector2(1.36f, 0.08f));
            UpdateOrCreateQuad(_fixturesRoot, "Elevator Penthouse Louver", RoofBallastColor,
                new Vector3(shaftX + 0.28f, deckTopY + 0.50f, 0.08f),
                new Vector2(0.42f, 0.32f));

            // Rooftop HVAC Chiller Unit
            var hvacX = shaftX + 2.4f;
            if (hvacX < roofRight - 1.2f)
            {
                UpdateOrCreateQuad(_fixturesRoot, "Rooftop HVAC Chiller", FixtureMetalColor,
                    new Vector3(hvacX, deckTopY + 0.28f, 0.14f),
                    new Vector2(0.85f, 0.56f));
                UpdateOrCreateQuad(_fixturesRoot, "HVAC Fan Cowling L", RoofBallastColor,
                    new Vector3(hvacX - 0.20f, deckTopY + 0.59f, 0.11f),
                    new Vector2(0.28f, 0.08f));
                UpdateOrCreateQuad(_fixturesRoot, "HVAC Fan Cowling R", RoofBallastColor,
                    new Vector3(hvacX + 0.20f, deckTopY + 0.59f, 0.11f),
                    new Vector2(0.28f, 0.08f));
            }

            // Communications Mast & Aviation Warning Light
            var mastX = roofLeft + 1.20f;
            UpdateOrCreateQuad(_fixturesRoot, "Communications Mast", DownspoutColor,
                new Vector3(mastX, deckTopY + 1.20f, 0.14f),
                new Vector2(0.06f, 2.40f));
            UpdateOrCreateQuad(_fixturesRoot, "Mast Cross Arm", DownspoutColor,
                new Vector3(mastX, deckTopY + 1.80f, 0.13f),
                new Vector2(0.40f, 0.04f));
            UpdateOrCreateQuad(_fixturesRoot, "Aviation Warning Beacon", BeaconGlowColor,
                new Vector3(mastX, deckTopY + 2.44f, -0.45f),
                new Vector2(0.12f, 0.12f));

            // Roof Access Hatch
            var hatchX = shaftX - 1.8f;
            if (hatchX > roofLeft + 0.8f)
            {
                UpdateOrCreateQuad(_fixturesRoot, "Roof Access Hatch", FixtureMetalColor,
                    new Vector3(hatchX, deckTopY + 0.22f, 0.14f),
                    new Vector2(0.55f, 0.44f));
            }
        }

        private void BuildSetbackTerraces(TowerTopologyProjection topology, int floorCount)
        {
            if (topology == null || floorCount <= 1) return;

            for (var f = 0; f < floorCount - 1; f++)
            {
                if (!topology.TryGetFloorSlab(f, out var lower) || !topology.TryGetFloorSlab(f + 1, out var upper)) continue;

                // Right-side Stepback
                if (lower.MaxX > upper.MaxX)
                {
                    var upperRight = -2.4f + (upper.MaxX + 1) * 0.5f;
                    var lowerRight = -2.4f + (lower.MaxX + 1) * 0.5f + WallThickness;
                    var terraceWidth = lowerRight - upperRight;
                    var terraceCenter = (upperRight + lowerRight) * 0.5f;
                    var terraceY = TowerStructurePresenter.FloorY(f + 1) - 0.74f;

                    UpdateOrCreateQuad(_terracesRoot, $"Terrace Slab R {f}", RoofDeckColor,
                        new Vector3(terraceCenter, terraceY + 0.08f, 0.15f),
                        new Vector2(terraceWidth, 0.16f));
                    UpdateOrCreateQuad(_terracesRoot, $"Terrace Railing R {f}", CorniceTrimColor,
                        new Vector3(terraceCenter, terraceY + 0.36f, 0.12f),
                        new Vector2(terraceWidth, 0.38f));
                }

                // Left-side Stepback
                if (lower.MinX < upper.MinX)
                {
                    var lowerLeft = -2.4f + lower.MinX * 0.5f - WallThickness;
                    var upperLeft = -2.4f + upper.MinX * 0.5f;
                    var terraceWidth = upperLeft - lowerLeft;
                    var terraceCenter = (lowerLeft + upperLeft) * 0.5f;
                    var terraceY = TowerStructurePresenter.FloorY(f + 1) - 0.74f;

                    UpdateOrCreateQuad(_terracesRoot, $"Terrace Slab L {f}", RoofDeckColor,
                        new Vector3(terraceCenter, terraceY + 0.08f, 0.15f),
                        new Vector2(terraceWidth, 0.16f));
                    UpdateOrCreateQuad(_terracesRoot, $"Terrace Railing L {f}", CorniceTrimColor,
                        new Vector3(terraceCenter, terraceY + 0.36f, 0.12f),
                        new Vector2(terraceWidth, 0.38f));
                }
            }
        }

        private void CalculateStageBounds(int floorCount, CellBounds ground, CellBounds top)
        {
            var groundLeft = -2.4f + ground.MinX * 0.5f - WallThickness;
            var groundRight = -2.4f + (ground.MaxX + 1) * 0.5f + WallThickness;
            var topFloorY = TowerStructurePresenter.FloorY(floorCount - 1) + 1.01f + RoofDeckThickness + ParapetHeight;
            var streetY = TowerStructurePresenter.FloorY(0) - 0.74f;

            var leftZone = new Bounds(
                new Vector3(groundLeft - 6.0f, (streetY + topFloorY) * 0.5f, 0f),
                new Vector3(12.0f, topFloorY - streetY + 10.0f, 10.0f));

            var rightZone = new Bounds(
                new Vector3(groundRight + 8.0f, (streetY + topFloorY) * 0.5f, 0f),
                new Vector3(16.0f, topFloorY - streetY + 10.0f, 10.0f));

            var rooftopZone = new Bounds(
                new Vector3((groundLeft + groundRight) * 0.5f, topFloorY + 4.0f, 0f),
                new Vector3(groundRight - groundLeft + 4.0f, 8.0f, 10.0f));

            var interiorEnclosure = new Bounds(
                new Vector3((groundLeft + groundRight) * 0.5f, (streetY + topFloorY) * 0.5f, 0.5f),
                new Vector3(groundRight - groundLeft, topFloorY - streetY, 2.0f));

            _stageBounds = new OutsideStageBounds(
                leftZone, rightZone, rooftopZone, interiorEnclosure,
                new Vector2(groundLeft, topFloorY), new Vector2(groundRight, topFloorY), topFloorY);
        }

        public void UpdateLighting(DayPhase phase)
        {
            UpdateAviationBeacons(phase);
            UpdateWindowLighting(phase);
        }

        private void UpdateAviationBeacons(DayPhase phase)
        {
            if (_fixturesRoot == null) return;
            // Beacon light pulses at night and dims by day
            var hour = phase.Hour + phase.Minute / 60f;
            var night = hour < 6f ? 1f : hour >= 18f ? 1f : 0f;
            var beacon = _fixturesRoot.Find("Aviation Warning Beacon");
            if (beacon != null)
            {
                var renderer = beacon.GetComponent<MeshRenderer>();
                if (renderer != null)
                {
                    var pulse = 0.5f + 0.5f * Mathf.Sin(Time.time * 4f);
                    var alpha = Mathf.Lerp(0.2f, 1.0f, night * pulse);
                    var col = new Color(BeaconGlowColor.r, BeaconGlowColor.g, BeaconGlowColor.b, alpha);
                    SetColor(renderer, col);
                }
            }
        }

        public void UpdateWindowLighting(DayPhase phase)
        {
            var hour = phase.Hour + phase.Minute / 60f;
            // Smooth continuous night factor: 1.0 fully at night, 0.0 fully by day.
            // Dawn ramp: 5.5h (full night) → 6.5h (full day). Dusk ramp: 19.5h → 20.5h.
            float smoothNight;
            if (hour < 5.5f || hour >= 20.5f)
                smoothNight = 1f;
            else if (hour < 6.5f)
                smoothNight = 6.5f - hour;          // 1.0 at 5.5h → 0.0 at 6.5h
            else if (hour < 19.5f)
                smoothNight = 0f;
            else
                smoothNight = hour - 19.5f;         // 0.0 at 19.5h → 1.0 at 20.5h

            for (var i = 0; i < _windowLightingEntries.Count; i++)
            {
                var entry = _windowLightingEntries[i];
                var isOccupied = entry.IsLeft
                    ? ((entry.Floor * 7 + 3) % 5 != 0)
                    : ((entry.Floor * 13 + 2) % 5 != 0);

                if (entry.GlassRenderer != null)
                {
                    var targetNightGlass = isOccupied ? WindowNightLitColor : WindowNightDarkColor;
                    var currentGlassColor = Color.Lerp(WindowDayColor, targetNightGlass, smoothNight);
                    SetColor(entry.GlassRenderer, currentGlassColor);
                }

                if (entry.ConeRenderer != null)
                {
                    var targetNightCone = isOccupied ? ConeNightLitColor : ConeNightDarkColor;
                    var currentConeColor = Color.Lerp(ConeDayColor, targetNightCone, smoothNight);
                    SetColor(entry.ConeRenderer, currentConeColor);
                }
            }
        }

        public void Clear()
        {
            if (_root != null)
            {
                if (UnityEngine.Application.isPlaying) Object.Destroy(_root.gameObject);
                else Object.DestroyImmediate(_root.gameObject);
            }

            for (var i = 0; i < _coneMeshes.Count; i++)
            {
                var m = _coneMeshes[i];
                if (m != null)
                {
                    if (UnityEngine.Application.isPlaying) Object.Destroy(m);
                    else Object.DestroyImmediate(m);
                }
            }
            _coneMeshes.Clear();

            _root = null;
            _leftFacadeRoot = null;
            _rightFacadeRoot = null;
            _rooflineRoot = null;
            _fixturesRoot = null;
            _terracesRoot = null;
            _volumetricLightRoot = null;

            _leftWallSlices.Clear();
            _rightWallSlices.Clear();
            _leftSpandrels.Clear();
            _rightSpandrels.Clear();
            _leftWindowFrames.Clear();
            _leftWindowGlasses.Clear();
            _leftWindowSills.Clear();
            _rightWindowFrames.Clear();
            _rightWindowGlasses.Clear();
            _rightWindowSills.Clear();
            _volumetricCones.Clear();
            _windowLightingEntries.Clear();
            _terraceObjects.Clear();
            _roofObjects.Clear();
            _renderedFloorCount = -1;
        }

        private GameObject UpdateOrCreateQuad(Transform parent, string name, Color color, Vector3 pos, Vector2 size, Material mat = null)
        {
            var child = parent.Find(name);
            GameObject go;
            MeshRenderer renderer;
            var targetMat = mat ?? _worldMaterial;
            if (child == null)
            {
                go = GameObject.CreatePrimitive(PrimitiveType.Quad);
                go.name = name;
                go.transform.SetParent(parent, false);
                var col = go.GetComponent<Collider>();
                if (col != null)
                {
                    if (UnityEngine.Application.isPlaying) Object.Destroy(col);
                    else Object.DestroyImmediate(col);
                }
                renderer = go.GetComponent<MeshRenderer>();
                renderer.sharedMaterial = targetMat;
            }
            else
            {
                go = child.gameObject;
                renderer = go.GetComponent<MeshRenderer>();
                if (targetMat != null) renderer.sharedMaterial = targetMat;
            }

            go.transform.localPosition = pos;
            go.transform.localScale = new Vector3(size.x, size.y, 1f);
            SetColor(renderer, color);
            return go;
        }

        private GameObject UpdateOrCreateLightCone(
            Transform parent, string name, Vector3 origin, float length, float direction)
        {
            if (parent == null) return null;
            var child = parent.Find(name);
            GameObject go;
            MeshFilter filter;
            MeshRenderer renderer;
            Mesh mesh;

            if (child == null)
            {
                go = new GameObject(name);
                go.transform.SetParent(parent, false);
                filter = go.AddComponent<MeshFilter>();
                renderer = go.AddComponent<MeshRenderer>();
                mesh = CreateLightConeMesh(origin, length, direction, name);
                filter.sharedMesh = mesh;
                _coneMeshes.Add(mesh);
            }
            else
            {
                go = child.gameObject;
                filter = go.GetComponent<MeshFilter>();
                if (filter == null) filter = go.AddComponent<MeshFilter>();
                renderer = go.GetComponent<MeshRenderer>();
                if (renderer == null) renderer = go.AddComponent<MeshRenderer>();

                mesh = filter.sharedMesh;
                if (mesh == null)
                {
                    mesh = CreateLightConeMesh(origin, length, direction, name);
                    filter.sharedMesh = mesh;
                    _coneMeshes.Add(mesh);
                }
                else
                {
                    UpdateLightConeMesh(mesh, origin, length, direction);
                }
            }

            go.transform.localPosition = new Vector3(0f, 0f, -0.20f);
            // Cones share the world material; transparency is achieved through vertex color
            // alpha gradient (tips = alpha 0) and the alpha blend mode on the shared material.
            if (_worldMaterial != null) renderer.sharedMaterial = _worldMaterial;
            SetColor(renderer, ConeDayColor);

            return go;
        }

        private static Mesh CreateLightConeMesh(Vector3 origin, float length, float direction, string name)
        {
            var mesh = new Mesh { name = name };
            UpdateLightConeMesh(mesh, origin, length, direction);
            return mesh;
        }

        private static void UpdateLightConeMesh(Mesh mesh, Vector3 origin, float length, float direction)
        {
            var v0 = new Vector3(origin.x, origin.y + 0.35f, 0f);
            var v1 = new Vector3(origin.x + direction * length, origin.y + 0.60f, 0f);
            var v2 = new Vector3(origin.x + direction * length, origin.y - 0.70f, 0f);
            var v3 = new Vector3(origin.x, origin.y - 0.35f, 0f);

            mesh.vertices = new[] { v0, v1, v2, v3 };
            mesh.triangles = new[]
            {
                0, 1, 2,
                0, 2, 3,
                0, 2, 1,
                0, 3, 2
            };
            mesh.colors = new[]
            {
                new Color(1f, 1f, 1f, 1f),
                new Color(1f, 1f, 1f, 0f),
                new Color(1f, 1f, 1f, 0f),
                new Color(1f, 1f, 1f, 1f)
            };
            mesh.uv = new[]
            {
                new Vector2(0f, 1f),
                new Vector2(1f, 1f),
                new Vector2(1f, 0f),
                new Vector2(0f, 0f)
            };
            mesh.RecalculateBounds();
        }


        private void SetColor(MeshRenderer renderer, Color color)
        {
            if (renderer == null) return;
            if (_worldMaterial != null && renderer.sharedMaterial != _worldMaterial)
                renderer.sharedMaterial = _worldMaterial;
            if (_colorBlock == null) _colorBlock = new MaterialPropertyBlock();
            renderer.GetPropertyBlock(_colorBlock);
            _colorBlock.SetColor("_BaseColor", color);
            _colorBlock.SetColor("_Color", color);
            renderer.SetPropertyBlock(_colorBlock);
        }
    }

    /// <summary>
    /// Immutable stage boundaries defining exterior atmospheric space and interior cutaway enclosure.
    /// </summary>
    public readonly struct OutsideStageBounds
    {
        public OutsideStageBounds(
            Bounds leftZone, Bounds rightZone, Bounds rooftopZone, Bounds interiorEnclosure,
            Vector2 leftScupper, Vector2 rightScupper, float roofDeckY)
        {
            LeftExteriorZone = leftZone;
            RightExteriorZone = rightZone;
            RooftopZone = rooftopZone;
            InteriorCutawayEnclosure = interiorEnclosure;
            LeftScupper = leftScupper;
            RightScupper = rightScupper;
            RoofDeckY = roofDeckY;
        }

        public Bounds LeftExteriorZone { get; }
        public Bounds RightExteriorZone { get; }
        public Bounds RooftopZone { get; }
        public Bounds InteriorCutawayEnclosure { get; }
        public Vector2 LeftScupper { get; }
        public Vector2 RightScupper { get; }
        public float RoofDeckY { get; }
    }
}
